-- 0030_content_product_domain — Atelier/PA "content / product / strategy".
--
-- Down-mapped from royalti-pa Supabase migrations:
--   002_cfo_schema.sql (strategic_initiatives, risk_register)
--   003_phase2_schema.sql (product_features)
--   004_phase3_schema.sql (content_calendar, tech_debt_items, metrics_snapshots)
--
-- strategic_initiatives is created here (not 0029) because product/content
-- tables soft-link to it; ordering within a single migration set is moot since
-- cross-domain FK REFERENCES are dropped, but keeping the strategy backbone
-- with the product domain matches PART A's grouping. numeric → TEXT, text[] →
-- TEXT (JSON), jsonb → TEXT, boolean → INTEGER. FK REFERENCES dropped.

CREATE TABLE IF NOT EXISTS strategic_initiatives (
  id TEXT PRIMARY KEY,
  quarter TEXT NOT NULL,
  wip_slot INTEGER,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'queued',
  owner_agent TEXT NOT NULL,
  supporting_agents TEXT,
  ties_to_goal INTEGER DEFAULT 0,
  uses_vehicle INTEGER DEFAULT 0,
  addresses_bottleneck INTEGER DEFAULT 0,
  rationale TEXT,
  success_criteria TEXT,
  key_deliverables TEXT,
  deadline TEXT,
  progress_pct INTEGER DEFAULT 0,
  deliverables_completed TEXT,
  budget_monthly_usd TEXT,
  budget_channel TEXT,
  budget_approach TEXT,
  blocked_by TEXT,
  estimated_start TEXT,
  extra TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS risk_register (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  severity TEXT NOT NULL,
  probability TEXT NOT NULL,
  probability_pct INTEGER,
  impact TEXT,
  mitigation_strategy TEXT,
  owner TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  timeline TEXT,
  trigger_condition TEXT,
  initiative_id TEXT,
  mitigation_task_id TEXT,
  last_reviewed TEXT,
  next_review TEXT,
  review_notes TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS product_features (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  user_story TEXT,
  pain_point TEXT,
  status TEXT NOT NULL DEFAULT 'idea',
  source TEXT,
  requested_by TEXT,
  requested_date TEXT,
  rice_reach TEXT,
  rice_impact TEXT,
  rice_confidence INTEGER,
  rice_effort TEXT,
  rice_score TEXT,
  progress_pct INTEGER DEFAULT 0,
  target_quarter TEXT,
  shipped_date TEXT,
  strategic_theme TEXT,
  initiative_id TEXT,
  partnership_id TEXT,
  adoption_rate TEXT,
  satisfaction_score TEXT,
  revenue_impact_usd TEXT,
  outcome_notes TEXT,
  extra TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS content_calendar (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  channel TEXT NOT NULL,
  platform TEXT,
  title TEXT NOT NULL,
  slug TEXT,
  status TEXT NOT NULL DEFAULT 'planned',
  assigned_to TEXT,
  publish_date TEXT,
  publish_time TEXT,
  actual_publish_date TEXT,
  campaign TEXT,
  series_name TEXT,
  series_part INTEGER,
  word_count INTEGER,
  seo_score INTEGER,
  editorial_score INTEGER,
  target_audience TEXT,
  primary_keyword TEXT,
  cta TEXT,
  workflow_stage TEXT,
  quality_gates_passed INTEGER DEFAULT 0,
  depends_on TEXT,
  promotes TEXT,
  views INTEGER,
  clicks INTEGER,
  conversions INTEGER,
  conversion_rate TEXT,
  engagement_rate TEXT,
  bounce_rate TEXT,
  avg_time_on_page TEXT,
  impressions INTEGER,
  open_rate TEXT,
  click_rate TEXT,
  initiative_id TEXT,
  folder_path TEXT,
  extra TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS tech_debt_items (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  area TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'identified',
  impact_score INTEGER,
  effort_score INTEGER,
  age_months INTEGER DEFAULT 0,
  debt_interest TEXT,
  priority_score TEXT,
  business_risk INTEGER,
  velocity_impact INTEGER,
  scalability_blocker INTEGER,
  security_concern INTEGER,
  time_days INTEGER,
  complexity INTEGER,
  regression_risk INTEGER,
  dependency_count INTEGER,
  remediation_plan TEXT,
  assigned_to TEXT,
  target_quarter TEXT,
  resolved_date TEXT,
  resolution_notes TEXT,
  adr_id TEXT,
  initiative_id TEXT,
  related_risk_id TEXT,
  discovered_date TEXT,
  last_assessed TEXT,
  extra TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS metrics_snapshots (
  id TEXT PRIMARY KEY,
  snapshot_date TEXT NOT NULL,
  period_type TEXT NOT NULL,
  period_label TEXT NOT NULL,
  domain TEXT NOT NULL,
  source_agent TEXT,
  metrics TEXT NOT NULL,
  data_completeness TEXT,
  validated_by TEXT,
  validation_notes TEXT,
  has_warnings INTEGER DEFAULT 0,
  has_critical INTEGER DEFAULT 0,
  alerts TEXT,
  created_at TEXT,
  updated_at TEXT
) STRICT;
