/* Canonical PausedDraft fixtures for the approve-gate panel.
 *
 * Salvaged from the locked D-04 pane + plans/atelier-design-system/designs/_fixtures/README.md
 * (Valentim de Carvalho · SMTP outreach; L5 Winback newsletter · Listmonk). Two more rows added
 * to exercise the overdue/cold and Buffer/social variants. The live panel receives `drafts` as a
 * prop from the renderer (the pa-action-paused payload); these stand in for the fixture harness
 * and the render/a11y tests until that seam lands. */

import type { PausedDraft } from './approve-gate-panel';

export const APPROVE_GATE_FIXTURES: PausedDraft[] = [
	{
		id: '4f8e2',
		recipient: 'Valentim de Carvalho',
		recipientEmail: 'valentim@valentimdc.pt',
		tenantId: '590',
		subject: 'Re: Catalog import — files ready for processing',
		bodyPreview:
			'Olá Valentim — recebido. O zero em v_sales_data é uma divergência de schema entre Pandora e Physical (já temos um patch); o cálculo só corre depois disso…',
		body: 'Olá Valentim,\n\nRecebido. O zero em v_sales_data é uma divergência de schema entre Pandora e Physical (já temos um patch); o cálculo só corre depois disso.\n\nVou processar agora e mando os números até ao fim do dia.\n\nUm abraço,\nChinedum',
		channel: 'smtp',
		agent: 'PA',
		senderAddress: 'chinedum@royalti.io',
		cold: false,
		status: 'edited',
		scheduledAt: '17:00 today',
		scheduledLabel: 'Scheduled · 17:00',
		timeVariant: 'is-today',
		overdue: false,
		everEdited: true,
		section: 'Today',
		sequence: null,
		fromProvider: 'SMTP · Fastmail',
		model: 'Opus 4.7',
		threadCount: '7 of 7',
		deal: 'Valentim',
		consequence: {
			target: 'Valentim',
			recipients: 1,
			channel: 'SMTP',
			time: '17:00 today',
			undoMs: 10000,
		},
	},
	{
		id: 'rs-91c2',
		recipient: 'Hannah Ekudo',
		recipientEmail: 'h.ekudo@bmg.com',
		tenantId: null,
		subject: 'Royalti × BMG — a quick intro on catalog ops',
		bodyPreview:
			"Hi Hannah — Chinedum here, founder at Royalti. We run the back-office (royalties, splits, outbound) for a handful of independent catalogs and I'd love 15 minutes…",
		body: "Hi Hannah,\n\nChinedum here, founder at Royalti. We run the back-office — royalties, splits, outbound — for a handful of independent catalogs, and I'd love 15 minutes to compare notes on how BMG handles catalog ops at scale.\n\nWorth a short call next week?\n\nBest,\nChinedum",
		channel: 'resend',
		agent: 'CBO',
		senderAddress: 'chinedum@royalti.io',
		cold: true,
		status: 'overdue',
		scheduledAt: 'yesterday 09:00',
		scheduledLabel: 'Overdue · yesterday 09:00',
		timeVariant: 'is-overdue',
		overdue: true,
		everEdited: false,
		section: 'Overdue',
		sequence: null,
		fromProvider: 'Resend',
		model: 'Opus 4.7',
		threadCount: '1 of 1',
		deal: null,
		consequence: {
			target: 'Hannah Ekudo',
			recipients: 1,
			channel: 'Resend',
			time: 'now',
			undoMs: 10000,
		},
	},
	{
		id: 'nl-3b9c1',
		recipient: 'L5 Winback · 388 recipients',
		recipientEmail: null,
		tenantId: null,
		subject: 'April · "Six things changed in your tenant this month"',
		bodyPreview:
			'Hi {{first_name}} — quick April note from Royalti. We shipped six tenant-side improvements that touch your catalog and your sends. Skim 60 seconds…',
		body: 'Hi {{first_name}} — quick April note from Royalti.\n\nWe shipped six tenant-side improvements that touch your catalog and your sends. Skim them in 60 seconds and tell us which one to walk you through.\n\n— The Royalti team',
		channel: 'listmonk',
		agent: 'CMO',
		senderAddress: 'finance@royalti.io',
		cold: false,
		status: 'awaiting',
		scheduledAt: 'Mon 09:00',
		scheduledLabel: 'Scheduled · Mon 09:00',
		timeVariant: null,
		overdue: false,
		everEdited: false,
		section: 'This week',
		sequence: { name: 'L5 Winback', step: 3, total: 5, recipients: 388 },
		fromProvider: 'Listmonk',
		model: 'Sonnet 4.6',
		threadCount: '1 of 1',
		deal: null,
		consequence: {
			target: 'L5 Winback list',
			recipients: 388,
			channel: 'Listmonk',
			time: 'Mon 09:00',
			undoMs: 10000,
		},
	},
	{
		id: 'soc-77a0',
		recipient: 'LinkedIn · Royalti company page',
		recipientEmail: null,
		tenantId: null,
		subject: 'Ship note: tenant-side improvements, April',
		bodyPreview:
			'Six things changed in your Royalti tenant this month — from faster catalog imports to tighter split coverage. A 60-second skim 👇',
		body: 'Six things changed in your Royalti tenant this month — from faster catalog imports to tighter split coverage.\n\nA 60-second skim 👇',
		channel: 'buffer',
		agent: 'CMO',
		senderAddress: 'social@royalti.io',
		cold: false,
		status: 'awaiting',
		scheduledAt: '16:30 today',
		scheduledLabel: 'Scheduled · 16:30',
		timeVariant: 'is-today',
		overdue: false,
		everEdited: false,
		section: 'Today',
		sequence: null,
		fromProvider: 'Buffer',
		model: 'Sonnet 4.6',
		threadCount: '1 of 1',
		deal: null,
		consequence: {
			target: 'LinkedIn company page',
			recipients: 1,
			channel: 'Buffer',
			time: '16:30 today',
			undoMs: 10000,
		},
	},
];
