/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiroutesSmokeRouteImport } from './routes/uiroutes-smoke'
import { Route as SettingsSmokeRouteImport } from './routes/settings-smoke'
import { Route as PkgSmokeRouteImport } from './routes/pkg-smoke'
import { Route as PkgKernelStatusRouteImport } from './routes/pkg-kernel-status'
import { Route as PermsSmokeRouteImport } from './routes/perms-smoke'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as McpSmokeRouteImport } from './routes/mcp-smoke'
import { Route as IykeSmokeRouteImport } from './routes/iyke-smoke'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IframeMountSmokeRouteImport } from './routes/iframe-mount-smoke'
import { Route as CronSmokeRouteImport } from './routes/cron-smoke'
import { Route as ClaudeAssetsSmokeRouteImport } from './routes/claude-assets-smoke'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ClaudeRouteRouteImport } from './routes/claude/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ClaudeIndexRouteImport } from './routes/claude/index'
import { Route as SettingsTelemetryRouteImport } from './routes/settings/telemetry'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsPackagesRouteImport } from './routes/settings/packages'
import { Route as SettingsOnboardingRouteImport } from './routes/settings/onboarding'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAgentRouteImport } from './routes/settings/agent'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingTelemetryRouteImport } from './routes/onboarding/telemetry'
import { Route as OnboardingSummaryRouteImport } from './routes/onboarding/summary'
import { Route as OnboardingScaffoldingRouteImport } from './routes/onboarding/scaffolding'
import { Route as OnboardingRootsRouteImport } from './routes/onboarding/roots'
import { Route as OnboardingPackagesRouteImport } from './routes/onboarding/packages'
import { Route as OnboardingConnectorsRouteImport } from './routes/onboarding/connectors'
import { Route as OnboardingAppearanceRouteImport } from './routes/onboarding/appearance'
import { Route as OnboardingAgentRouteImport } from './routes/onboarding/agent'
import { Route as ClaudeSkillsRouteImport } from './routes/claude/skills'
import { Route as ClaudeMcpsRouteImport } from './routes/claude/mcps'
import { Route as ClaudeHooksRouteImport } from './routes/claude/hooks'
import { Route as ClaudeCommandsRouteImport } from './routes/claude/commands'
import { Route as PkgPkgIdRouteRouteImport } from './routes/pkg/$pkgId/route'
import { Route as SessionsByAgentIndexRouteImport } from './routes/sessions/by-agent/index'
import { Route as SessionsAllIndexRouteImport } from './routes/sessions/all/index'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as PkgPkgIdIndexRouteImport } from './routes/pkg/$pkgId/index'
import { Route as SessionsByAgentAgentRouteImport } from './routes/sessions/by-agent/$agent'
import { Route as PkgPkgIdSplatRouteImport } from './routes/pkg/$pkgId/$'

const UiroutesSmokeRoute = UiroutesSmokeRouteImport.update({
  id: '/uiroutes-smoke',
  path: '/uiroutes-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSmokeRoute = SettingsSmokeRouteImport.update({
  id: '/settings-smoke',
  path: '/settings-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgSmokeRoute = PkgSmokeRouteImport.update({
  id: '/pkg-smoke',
  path: '/pkg-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgKernelStatusRoute = PkgKernelStatusRouteImport.update({
  id: '/pkg-kernel-status',
  path: '/pkg-kernel-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PermsSmokeRoute = PermsSmokeRouteImport.update({
  id: '/perms-smoke',
  path: '/perms-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSmokeRoute = McpSmokeRouteImport.update({
  id: '/mcp-smoke',
  path: '/mcp-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IykeSmokeRoute = IykeSmokeRouteImport.update({
  id: '/iyke-smoke',
  path: '/iyke-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeMountSmokeRoute = IframeMountSmokeRouteImport.update({
  id: '/iframe-mount-smoke',
  path: '/iframe-mount-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CronSmokeRoute = CronSmokeRouteImport.update({
  id: '/cron-smoke',
  path: '/cron-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeAssetsSmokeRoute = ClaudeAssetsSmokeRouteImport.update({
  id: '/claude-assets-smoke',
  path: '/claude-assets-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRouteRoute = ClaudeRouteRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ClaudeIndexRoute = ClaudeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const SettingsTelemetryRoute = SettingsTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPackagesRoute = SettingsPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOnboardingRoute = SettingsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingTelemetryRoute = OnboardingTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingSummaryRoute = OnboardingSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingScaffoldingRoute = OnboardingScaffoldingRouteImport.update({
  id: '/scaffolding',
  path: '/scaffolding',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingRootsRoute = OnboardingRootsRouteImport.update({
  id: '/roots',
  path: '/roots',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPackagesRoute = OnboardingPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConnectorsRoute = OnboardingConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAppearanceRoute = OnboardingAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAgentRoute = OnboardingAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeMcpsRoute = ClaudeMcpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeHooksRoute = ClaudeHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeCommandsRoute = ClaudeCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const PkgPkgIdRouteRoute = PkgPkgIdRouteRouteImport.update({
  id: '/pkg/$pkgId',
  path: '/pkg/$pkgId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsByAgentIndexRoute = SessionsByAgentIndexRouteImport.update({
  id: '/by-agent/',
  path: '/by-agent/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsAllIndexRoute = SessionsAllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/$sessionId/',
  path: '/$sessionId/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const PkgPkgIdIndexRoute = PkgPkgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkgPkgIdRouteRoute,
} as any)
const SessionsByAgentAgentRoute = SessionsByAgentAgentRouteImport.update({
  id: '/by-agent/$agent',
  path: '/by-agent/$agent',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const PkgPkgIdSplatRoute = PkgPkgIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PkgPkgIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/telemetry': typeof OnboardingTelemetryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/telemetry': typeof SettingsTelemetryRoute
  '/claude/': typeof ClaudeIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/pkg/$pkgId/': typeof PkgPkgIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/telemetry': typeof OnboardingTelemetryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/telemetry': typeof SettingsTelemetryRoute
  '/claude': typeof ClaudeIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/pkg/$pkgId': typeof PkgPkgIdIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/sessions/all': typeof SessionsAllIndexRoute
  '/sessions/by-agent': typeof SessionsByAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/appearance': typeof OnboardingAppearanceRoute
  '/onboarding/connectors': typeof OnboardingConnectorsRoute
  '/onboarding/packages': typeof OnboardingPackagesRoute
  '/onboarding/roots': typeof OnboardingRootsRoute
  '/onboarding/scaffolding': typeof OnboardingScaffoldingRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/onboarding/telemetry': typeof OnboardingTelemetryRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/onboarding': typeof SettingsOnboardingRoute
  '/settings/packages': typeof SettingsPackagesRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/telemetry': typeof SettingsTelemetryRoute
  '/claude/': typeof ClaudeIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/pkg/$pkgId/': typeof PkgPkgIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude'
    | '/onboarding'
    | '/sessions'
    | '/settings'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/uiroutes-smoke'
    | '/pkg/$pkgId'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/telemetry'
    | '/onboarding/welcome'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/storage'
    | '/settings/telemetry'
    | '/claude/'
    | '/onboarding/'
    | '/sessions/'
    | '/settings/'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/pkg/$pkgId/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/uiroutes-smoke'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/telemetry'
    | '/onboarding/welcome'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/storage'
    | '/settings/telemetry'
    | '/claude'
    | '/onboarding'
    | '/sessions'
    | '/settings'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/pkg/$pkgId'
    | '/sessions/$sessionId'
    | '/sessions/all'
    | '/sessions/by-agent'
  id:
    | '__root__'
    | '/'
    | '/claude'
    | '/onboarding'
    | '/sessions'
    | '/settings'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/uiroutes-smoke'
    | '/pkg/$pkgId'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/onboarding/agent'
    | '/onboarding/appearance'
    | '/onboarding/connectors'
    | '/onboarding/packages'
    | '/onboarding/roots'
    | '/onboarding/scaffolding'
    | '/onboarding/summary'
    | '/onboarding/telemetry'
    | '/onboarding/welcome'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/integrations'
    | '/settings/onboarding'
    | '/settings/packages'
    | '/settings/storage'
    | '/settings/telemetry'
    | '/claude/'
    | '/onboarding/'
    | '/sessions/'
    | '/settings/'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/pkg/$pkgId/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeRouteRoute: typeof ClaudeRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ClaudeAssetsSmokeRoute: typeof ClaudeAssetsSmokeRoute
  CronSmokeRoute: typeof CronSmokeRoute
  IframeMountSmokeRoute: typeof IframeMountSmokeRoute
  InstallRoute: typeof InstallRoute
  IykeSmokeRoute: typeof IykeSmokeRoute
  McpSmokeRoute: typeof McpSmokeRoute
  PackagesRoute: typeof PackagesRoute
  PermsSmokeRoute: typeof PermsSmokeRoute
  PkgKernelStatusRoute: typeof PkgKernelStatusRoute
  PkgSmokeRoute: typeof PkgSmokeRoute
  SettingsSmokeRoute: typeof SettingsSmokeRoute
  UiroutesSmokeRoute: typeof UiroutesSmokeRoute
  PkgPkgIdRouteRoute: typeof PkgPkgIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uiroutes-smoke': {
      id: '/uiroutes-smoke'
      path: '/uiroutes-smoke'
      fullPath: '/uiroutes-smoke'
      preLoaderRoute: typeof UiroutesSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-smoke': {
      id: '/settings-smoke'
      path: '/settings-smoke'
      fullPath: '/settings-smoke'
      preLoaderRoute: typeof SettingsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-smoke': {
      id: '/pkg-smoke'
      path: '/pkg-smoke'
      fullPath: '/pkg-smoke'
      preLoaderRoute: typeof PkgSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-kernel-status': {
      id: '/pkg-kernel-status'
      path: '/pkg-kernel-status'
      fullPath: '/pkg-kernel-status'
      preLoaderRoute: typeof PkgKernelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perms-smoke': {
      id: '/perms-smoke'
      path: '/perms-smoke'
      fullPath: '/perms-smoke'
      preLoaderRoute: typeof PermsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-smoke': {
      id: '/mcp-smoke'
      path: '/mcp-smoke'
      fullPath: '/mcp-smoke'
      preLoaderRoute: typeof McpSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iyke-smoke': {
      id: '/iyke-smoke'
      path: '/iyke-smoke'
      fullPath: '/iyke-smoke'
      preLoaderRoute: typeof IykeSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-mount-smoke': {
      id: '/iframe-mount-smoke'
      path: '/iframe-mount-smoke'
      fullPath: '/iframe-mount-smoke'
      preLoaderRoute: typeof IframeMountSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-smoke': {
      id: '/cron-smoke'
      path: '/cron-smoke'
      fullPath: '/cron-smoke'
      preLoaderRoute: typeof CronSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-assets-smoke': {
      id: '/claude-assets-smoke'
      path: '/claude-assets-smoke'
      fullPath: '/claude-assets-smoke'
      preLoaderRoute: typeof ClaudeAssetsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/claude/': {
      id: '/claude/'
      path: '/'
      fullPath: '/claude/'
      preLoaderRoute: typeof ClaudeIndexRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/settings/telemetry': {
      id: '/settings/telemetry'
      path: '/telemetry'
      fullPath: '/settings/telemetry'
      preLoaderRoute: typeof SettingsTelemetryRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/packages': {
      id: '/settings/packages'
      path: '/packages'
      fullPath: '/settings/packages'
      preLoaderRoute: typeof SettingsPackagesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/onboarding': {
      id: '/settings/onboarding'
      path: '/onboarding'
      fullPath: '/settings/onboarding'
      preLoaderRoute: typeof SettingsOnboardingRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/agent': {
      id: '/settings/agent'
      path: '/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/telemetry': {
      id: '/onboarding/telemetry'
      path: '/telemetry'
      fullPath: '/onboarding/telemetry'
      preLoaderRoute: typeof OnboardingTelemetryRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/summary': {
      id: '/onboarding/summary'
      path: '/summary'
      fullPath: '/onboarding/summary'
      preLoaderRoute: typeof OnboardingSummaryRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/scaffolding': {
      id: '/onboarding/scaffolding'
      path: '/scaffolding'
      fullPath: '/onboarding/scaffolding'
      preLoaderRoute: typeof OnboardingScaffoldingRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/roots': {
      id: '/onboarding/roots'
      path: '/roots'
      fullPath: '/onboarding/roots'
      preLoaderRoute: typeof OnboardingRootsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/packages': {
      id: '/onboarding/packages'
      path: '/packages'
      fullPath: '/onboarding/packages'
      preLoaderRoute: typeof OnboardingPackagesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/connectors': {
      id: '/onboarding/connectors'
      path: '/connectors'
      fullPath: '/onboarding/connectors'
      preLoaderRoute: typeof OnboardingConnectorsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/appearance': {
      id: '/onboarding/appearance'
      path: '/appearance'
      fullPath: '/onboarding/appearance'
      preLoaderRoute: typeof OnboardingAppearanceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/agent': {
      id: '/onboarding/agent'
      path: '/agent'
      fullPath: '/onboarding/agent'
      preLoaderRoute: typeof OnboardingAgentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/claude/skills': {
      id: '/claude/skills'
      path: '/skills'
      fullPath: '/claude/skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/mcps': {
      id: '/claude/mcps'
      path: '/mcps'
      fullPath: '/claude/mcps'
      preLoaderRoute: typeof ClaudeMcpsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/hooks': {
      id: '/claude/hooks'
      path: '/hooks'
      fullPath: '/claude/hooks'
      preLoaderRoute: typeof ClaudeHooksRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/commands': {
      id: '/claude/commands'
      path: '/commands'
      fullPath: '/claude/commands'
      preLoaderRoute: typeof ClaudeCommandsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/pkg/$pkgId': {
      id: '/pkg/$pkgId'
      path: '/pkg/$pkgId'
      fullPath: '/pkg/$pkgId'
      preLoaderRoute: typeof PkgPkgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/by-agent/': {
      id: '/sessions/by-agent/'
      path: '/by-agent'
      fullPath: '/sessions/by-agent/'
      preLoaderRoute: typeof SessionsByAgentIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/all/': {
      id: '/sessions/all/'
      path: '/all'
      fullPath: '/sessions/all/'
      preLoaderRoute: typeof SessionsAllIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/pkg/$pkgId/': {
      id: '/pkg/$pkgId/'
      path: '/'
      fullPath: '/pkg/$pkgId/'
      preLoaderRoute: typeof PkgPkgIdIndexRouteImport
      parentRoute: typeof PkgPkgIdRouteRoute
    }
    '/sessions/by-agent/$agent': {
      id: '/sessions/by-agent/$agent'
      path: '/by-agent/$agent'
      fullPath: '/sessions/by-agent/$agent'
      preLoaderRoute: typeof SessionsByAgentAgentRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/pkg/$pkgId/$': {
      id: '/pkg/$pkgId/$'
      path: '/$'
      fullPath: '/pkg/$pkgId/$'
      preLoaderRoute: typeof PkgPkgIdSplatRouteImport
      parentRoute: typeof PkgPkgIdRouteRoute
    }
  }
}

interface ClaudeRouteRouteChildren {
  ClaudeCommandsRoute: typeof ClaudeCommandsRoute
  ClaudeHooksRoute: typeof ClaudeHooksRoute
  ClaudeMcpsRoute: typeof ClaudeMcpsRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  ClaudeIndexRoute: typeof ClaudeIndexRoute
}

const ClaudeRouteRouteChildren: ClaudeRouteRouteChildren = {
  ClaudeCommandsRoute: ClaudeCommandsRoute,
  ClaudeHooksRoute: ClaudeHooksRoute,
  ClaudeMcpsRoute: ClaudeMcpsRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  ClaudeIndexRoute: ClaudeIndexRoute,
}

const ClaudeRouteRouteWithChildren = ClaudeRouteRoute._addFileChildren(
  ClaudeRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingAgentRoute: typeof OnboardingAgentRoute
  OnboardingAppearanceRoute: typeof OnboardingAppearanceRoute
  OnboardingConnectorsRoute: typeof OnboardingConnectorsRoute
  OnboardingPackagesRoute: typeof OnboardingPackagesRoute
  OnboardingRootsRoute: typeof OnboardingRootsRoute
  OnboardingScaffoldingRoute: typeof OnboardingScaffoldingRoute
  OnboardingSummaryRoute: typeof OnboardingSummaryRoute
  OnboardingTelemetryRoute: typeof OnboardingTelemetryRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAgentRoute: OnboardingAgentRoute,
  OnboardingAppearanceRoute: OnboardingAppearanceRoute,
  OnboardingConnectorsRoute: OnboardingConnectorsRoute,
  OnboardingPackagesRoute: OnboardingPackagesRoute,
  OnboardingRootsRoute: OnboardingRootsRoute,
  OnboardingScaffoldingRoute: OnboardingScaffoldingRoute,
  OnboardingSummaryRoute: OnboardingSummaryRoute,
  OnboardingTelemetryRoute: OnboardingTelemetryRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsByAgentAgentRoute: typeof SessionsByAgentAgentRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  SessionsAllIndexRoute: typeof SessionsAllIndexRoute
  SessionsByAgentIndexRoute: typeof SessionsByAgentIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsByAgentAgentRoute: SessionsByAgentAgentRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  SessionsAllIndexRoute: SessionsAllIndexRoute,
  SessionsByAgentIndexRoute: SessionsByAgentIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsOnboardingRoute: typeof SettingsOnboardingRoute
  SettingsPackagesRoute: typeof SettingsPackagesRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsTelemetryRoute: typeof SettingsTelemetryRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsOnboardingRoute: SettingsOnboardingRoute,
  SettingsPackagesRoute: SettingsPackagesRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsTelemetryRoute: SettingsTelemetryRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface PkgPkgIdRouteRouteChildren {
  PkgPkgIdSplatRoute: typeof PkgPkgIdSplatRoute
  PkgPkgIdIndexRoute: typeof PkgPkgIdIndexRoute
}

const PkgPkgIdRouteRouteChildren: PkgPkgIdRouteRouteChildren = {
  PkgPkgIdSplatRoute: PkgPkgIdSplatRoute,
  PkgPkgIdIndexRoute: PkgPkgIdIndexRoute,
}

const PkgPkgIdRouteRouteWithChildren = PkgPkgIdRouteRoute._addFileChildren(
  PkgPkgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeRouteRoute: ClaudeRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ClaudeAssetsSmokeRoute: ClaudeAssetsSmokeRoute,
  CronSmokeRoute: CronSmokeRoute,
  IframeMountSmokeRoute: IframeMountSmokeRoute,
  InstallRoute: InstallRoute,
  IykeSmokeRoute: IykeSmokeRoute,
  McpSmokeRoute: McpSmokeRoute,
  PackagesRoute: PackagesRoute,
  PermsSmokeRoute: PermsSmokeRoute,
  PkgKernelStatusRoute: PkgKernelStatusRoute,
  PkgSmokeRoute: PkgSmokeRoute,
  SettingsSmokeRoute: SettingsSmokeRoute,
  UiroutesSmokeRoute: UiroutesSmokeRoute,
  PkgPkgIdRouteRoute: PkgPkgIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
