/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiroutesSmokeRouteImport } from './routes/uiroutes-smoke'
import { Route as SweeperRouteImport } from './routes/sweeper'
import { Route as SpikeAclRouteImport } from './routes/spike-acl'
import { Route as SettingsSmokeRouteImport } from './routes/settings-smoke'
import { Route as PkgSmokeRouteImport } from './routes/pkg-smoke'
import { Route as PkgKernelStatusRouteImport } from './routes/pkg-kernel-status'
import { Route as PermsSmokeRouteImport } from './routes/perms-smoke'
import { Route as McpSmokeRouteImport } from './routes/mcp-smoke'
import { Route as IykeSmokeRouteImport } from './routes/iyke-smoke'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IframeMountSmokeRouteImport } from './routes/iframe-mount-smoke'
import { Route as CronSmokeRouteImport } from './routes/cron-smoke'
import { Route as ClaudeAssetsSmokeRouteImport } from './routes/claude-assets-smoke'
import { Route as VideoRouteRouteImport } from './routes/video/route'
import { Route as StoryboardRouteRouteImport } from './routes/storyboard/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as OutboxRouteRouteImport } from './routes/outbox/route'
import { Route as MailRouteRouteImport } from './routes/mail/route'
import { Route as FundraisingRouteRouteImport } from './routes/fundraising/route'
import { Route as FinanceRouteRouteImport } from './routes/finance/route'
import { Route as EmailsRouteRouteImport } from './routes/emails/route'
import { Route as EmailQueueRouteRouteImport } from './routes/email-queue/route'
import { Route as DelegationsRouteRouteImport } from './routes/delegations/route'
import { Route as ClaudeRouteRouteImport } from './routes/claude/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video/index'
import { Route as TriageIndexRouteImport } from './routes/triage/index'
import { Route as StrategyIndexRouteImport } from './routes/strategy/index'
import { Route as StoryboardIndexRouteImport } from './routes/storyboard/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as PartnershipsIndexRouteImport } from './routes/partnerships/index'
import { Route as OutboxIndexRouteImport } from './routes/outbox/index'
import { Route as MailIndexRouteImport } from './routes/mail/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as HandoffsIndexRouteImport } from './routes/handoffs/index'
import { Route as FundraisingIndexRouteImport } from './routes/fundraising/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as ExecutiveIndexRouteImport } from './routes/executive/index'
import { Route as EmailsIndexRouteImport } from './routes/emails/index'
import { Route as EmailQueueIndexRouteImport } from './routes/email-queue/index'
import { Route as DelegationsIndexRouteImport } from './routes/delegations/index'
import { Route as CronIndexRouteImport } from './routes/cron/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as ClaudeIndexRouteImport } from './routes/claude/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as AgentRunsIndexRouteImport } from './routes/agent-runs/index'
import { Route as VideoQueueRouteImport } from './routes/video/queue'
import { Route as VideoCompositionIdRouteImport } from './routes/video/$compositionId'
import { Route as StoryboardIdRouteImport } from './routes/storyboard/$id'
import { Route as ReportsIdRouteImport } from './routes/reports/$id'
import { Route as MailIdRouteImport } from './routes/mail/$id'
import { Route as HandoffsIdRouteImport } from './routes/handoffs/$id'
import { Route as EmailsIdRouteImport } from './routes/emails/$id'
import { Route as EmailQueueIdRouteImport } from './routes/email-queue/$id'
import { Route as DelegationsIdRouteImport } from './routes/delegations/$id'
import { Route as ClaudeSkillsRouteImport } from './routes/claude/skills'
import { Route as ClaudeMcpsRouteImport } from './routes/claude/mcps'
import { Route as ClaudeHooksRouteImport } from './routes/claude/hooks'
import { Route as ClaudeCommandsRouteImport } from './routes/claude/commands'
import { Route as OutboxSocialRouteRouteImport } from './routes/outbox/social/route'
import { Route as OutboxSequencesRouteRouteImport } from './routes/outbox/sequences/route'
import { Route as OutboxNewsletterRouteRouteImport } from './routes/outbox/newsletter/route'
import { Route as OutboxEmailRouteRouteImport } from './routes/outbox/email/route'
import { Route as FinanceTransactionsRouteRouteImport } from './routes/finance/transactions/route'
import { Route as SessionsByAgentIndexRouteImport } from './routes/sessions/by-agent/index'
import { Route as SessionsAllIndexRouteImport } from './routes/sessions/all/index'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as OutboxSocialIndexRouteImport } from './routes/outbox/social/index'
import { Route as OutboxSequencesIndexRouteImport } from './routes/outbox/sequences/index'
import { Route as OutboxSentIndexRouteImport } from './routes/outbox/sent/index'
import { Route as OutboxNewsletterIndexRouteImport } from './routes/outbox/newsletter/index'
import { Route as OutboxEmailIndexRouteImport } from './routes/outbox/email/index'
import { Route as MailTriageIndexRouteImport } from './routes/mail/triage/index'
import { Route as MailInboxIndexRouteImport } from './routes/mail/inbox/index'
import { Route as MailDraftsIndexRouteImport } from './routes/mail/drafts/index'
import { Route as MailAllIndexRouteImport } from './routes/mail/all/index'
import { Route as FundraisingApprovalsIndexRouteImport } from './routes/fundraising/approvals/index'
import { Route as FundraisingAnalyticsIndexRouteImport } from './routes/fundraising/analytics/index'
import { Route as FinanceReportsIndexRouteImport } from './routes/finance/reports/index'
import { Route as FinanceReceivablesIndexRouteImport } from './routes/finance/receivables/index'
import { Route as FinanceInterCompanyIndexRouteImport } from './routes/finance/inter-company/index'
import { Route as EmailsDraftsIndexRouteImport } from './routes/emails/drafts/index'
import { Route as EmailQueueSequencesIndexRouteImport } from './routes/email-queue/sequences/index'
import { Route as EmailQueueSentIndexRouteImport } from './routes/email-queue/sent/index'
import { Route as EmailQueueRepliesIndexRouteImport } from './routes/email-queue/replies/index'
import { Route as EmailQueueApprovalsIndexRouteImport } from './routes/email-queue/approvals/index'
import { Route as SessionsByAgentAgentRouteImport } from './routes/sessions/by-agent/$agent'
import { Route as PkgPkgIdSplatRouteImport } from './routes/pkg/$pkgId/$'
import { Route as FinanceTransactionsIdRouteImport } from './routes/finance/transactions/$id'
import { Route as OutboxSocialSentIndexRouteImport } from './routes/outbox/social/sent/index'
import { Route as OutboxSocialScheduleIndexRouteImport } from './routes/outbox/social/schedule/index'
import { Route as OutboxSocialQueueIndexRouteImport } from './routes/outbox/social/queue/index'
import { Route as OutboxSequencesSentIndexRouteImport } from './routes/outbox/sequences/sent/index'
import { Route as OutboxSequencesQueueIndexRouteImport } from './routes/outbox/sequences/queue/index'
import { Route as OutboxSequencesActiveIndexRouteImport } from './routes/outbox/sequences/active/index'
import { Route as OutboxNewsletterSentIndexRouteImport } from './routes/outbox/newsletter/sent/index'
import { Route as OutboxNewsletterScheduleIndexRouteImport } from './routes/outbox/newsletter/schedule/index'
import { Route as OutboxNewsletterQueueIndexRouteImport } from './routes/outbox/newsletter/queue/index'
import { Route as OutboxEmailSentIndexRouteImport } from './routes/outbox/email/sent/index'
import { Route as OutboxEmailScheduleIndexRouteImport } from './routes/outbox/email/schedule/index'
import { Route as OutboxEmailQueueIndexRouteImport } from './routes/outbox/email/queue/index'

const UiroutesSmokeRoute = UiroutesSmokeRouteImport.update({
  id: '/uiroutes-smoke',
  path: '/uiroutes-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SweeperRoute = SweeperRouteImport.update({
  id: '/sweeper',
  path: '/sweeper',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeAclRoute = SpikeAclRouteImport.update({
  id: '/spike-acl',
  path: '/spike-acl',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSmokeRoute = SettingsSmokeRouteImport.update({
  id: '/settings-smoke',
  path: '/settings-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgSmokeRoute = PkgSmokeRouteImport.update({
  id: '/pkg-smoke',
  path: '/pkg-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgKernelStatusRoute = PkgKernelStatusRouteImport.update({
  id: '/pkg-kernel-status',
  path: '/pkg-kernel-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PermsSmokeRoute = PermsSmokeRouteImport.update({
  id: '/perms-smoke',
  path: '/perms-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSmokeRoute = McpSmokeRouteImport.update({
  id: '/mcp-smoke',
  path: '/mcp-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IykeSmokeRoute = IykeSmokeRouteImport.update({
  id: '/iyke-smoke',
  path: '/iyke-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeMountSmokeRoute = IframeMountSmokeRouteImport.update({
  id: '/iframe-mount-smoke',
  path: '/iframe-mount-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CronSmokeRoute = CronSmokeRouteImport.update({
  id: '/cron-smoke',
  path: '/cron-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeAssetsSmokeRoute = ClaudeAssetsSmokeRouteImport.update({
  id: '/claude-assets-smoke',
  path: '/claude-assets-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRouteRoute = VideoRouteRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRouteRoute = StoryboardRouteRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxRouteRoute = OutboxRouteRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRouteRoute = MailRouteRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRouteRoute = FundraisingRouteRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRouteRoute = FinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRouteRoute = EmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailQueueRouteRoute = EmailQueueRouteRouteImport.update({
  id: '/email-queue',
  path: '/email-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegationsRouteRoute = DelegationsRouteRouteImport.update({
  id: '/delegations',
  path: '/delegations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRouteRoute = ClaudeRouteRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() => import('./routes/video/index.lazy').then((d) => d.Route))
const TriageIndexRoute = TriageIndexRouteImport.update({
  id: '/triage/',
  path: '/triage/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyIndexRoute = StrategyIndexRouteImport.update({
  id: '/strategy/',
  path: '/strategy/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardIndexRoute = StoryboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoryboardRouteRoute,
} as any).lazy(() =>
  import('./routes/storyboard/index.lazy').then((d) => d.Route),
)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsIndexRoute = PartnershipsIndexRouteImport.update({
  id: '/partnerships/',
  path: '/partnerships/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxIndexRoute = OutboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailRouteRoute,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsIndexRoute = HandoffsIndexRouteImport.update({
  id: '/handoffs/',
  path: '/handoffs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingIndexRoute = FundraisingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FundraisingRouteRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIndexRoute = ExecutiveIndexRouteImport.update({
  id: '/executive/',
  path: '/executive/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const EmailQueueIndexRoute = EmailQueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailQueueRouteRoute,
} as any)
const DelegationsIndexRoute = DelegationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DelegationsRouteRoute,
} as any)
const CronIndexRoute = CronIndexRouteImport.update({
  id: '/cron/',
  path: '/cron/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeIndexRoute = ClaudeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsIndexRoute = AgentRunsIndexRouteImport.update({
  id: '/agent-runs/',
  path: '/agent-runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoQueueRoute = VideoQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() => import('./routes/video/queue.lazy').then((d) => d.Route))
const VideoCompositionIdRoute = VideoCompositionIdRouteImport.update({
  id: '/$compositionId',
  path: '/$compositionId',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() =>
  import('./routes/video/$compositionId.lazy').then((d) => d.Route),
)
const StoryboardIdRoute = StoryboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoryboardRouteRoute,
} as any).lazy(() =>
  import('./routes/storyboard/$id.lazy').then((d) => d.Route),
)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIdRoute = MailIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MailRouteRoute,
} as any)
const HandoffsIdRoute = HandoffsIdRouteImport.update({
  id: '/handoffs/$id',
  path: '/handoffs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIdRoute = EmailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const EmailQueueIdRoute = EmailQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmailQueueRouteRoute,
} as any)
const DelegationsIdRoute = DelegationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DelegationsRouteRoute,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeMcpsRoute = ClaudeMcpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeHooksRoute = ClaudeHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeCommandsRoute = ClaudeCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const OutboxSocialRouteRoute = OutboxSocialRouteRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxSequencesRouteRoute = OutboxSequencesRouteRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxNewsletterRouteRoute = OutboxNewsletterRouteRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxEmailRouteRoute = OutboxEmailRouteRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const FinanceTransactionsRouteRoute =
  FinanceTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => FinanceRouteRoute,
  } as any)
const SessionsByAgentIndexRoute = SessionsByAgentIndexRouteImport.update({
  id: '/by-agent/',
  path: '/by-agent/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsAllIndexRoute = SessionsAllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/$sessionId/',
  path: '/$sessionId/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const OutboxSocialIndexRoute = OutboxSocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutboxSocialRouteRoute,
} as any)
const OutboxSequencesIndexRoute = OutboxSequencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutboxSequencesRouteRoute,
} as any)
const OutboxSentIndexRoute = OutboxSentIndexRouteImport.update({
  id: '/sent/',
  path: '/sent/',
  getParentRoute: () => OutboxRouteRoute,
} as any)
const OutboxNewsletterIndexRoute = OutboxNewsletterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutboxNewsletterRouteRoute,
} as any)
const OutboxEmailIndexRoute = OutboxEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutboxEmailRouteRoute,
} as any)
const MailTriageIndexRoute = MailTriageIndexRouteImport.update({
  id: '/triage/',
  path: '/triage/',
  getParentRoute: () => MailRouteRoute,
} as any)
const MailInboxIndexRoute = MailInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => MailRouteRoute,
} as any)
const MailDraftsIndexRoute = MailDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => MailRouteRoute,
} as any)
const MailAllIndexRoute = MailAllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => MailRouteRoute,
} as any)
const FundraisingApprovalsIndexRoute =
  FundraisingApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => FundraisingRouteRoute,
  } as any)
const FundraisingAnalyticsIndexRoute =
  FundraisingAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => FundraisingRouteRoute,
  } as any)
const FinanceReportsIndexRoute = FinanceReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const FinanceReceivablesIndexRoute = FinanceReceivablesIndexRouteImport.update({
  id: '/receivables/',
  path: '/receivables/',
  getParentRoute: () => FinanceRouteRoute,
} as any)
const FinanceInterCompanyIndexRoute =
  FinanceInterCompanyIndexRouteImport.update({
    id: '/inter-company/',
    path: '/inter-company/',
    getParentRoute: () => FinanceRouteRoute,
  } as any)
const EmailsDraftsIndexRoute = EmailsDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const EmailQueueSequencesIndexRoute =
  EmailQueueSequencesIndexRouteImport.update({
    id: '/sequences/',
    path: '/sequences/',
    getParentRoute: () => EmailQueueRouteRoute,
  } as any)
const EmailQueueSentIndexRoute = EmailQueueSentIndexRouteImport.update({
  id: '/sent/',
  path: '/sent/',
  getParentRoute: () => EmailQueueRouteRoute,
} as any)
const EmailQueueRepliesIndexRoute = EmailQueueRepliesIndexRouteImport.update({
  id: '/replies/',
  path: '/replies/',
  getParentRoute: () => EmailQueueRouteRoute,
} as any)
const EmailQueueApprovalsIndexRoute =
  EmailQueueApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => EmailQueueRouteRoute,
  } as any)
const SessionsByAgentAgentRoute = SessionsByAgentAgentRouteImport.update({
  id: '/by-agent/$agent',
  path: '/by-agent/$agent',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const PkgPkgIdSplatRoute = PkgPkgIdSplatRouteImport.update({
  id: '/pkg/$pkgId/$',
  path: '/pkg/$pkgId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsIdRoute = FinanceTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FinanceTransactionsRouteRoute,
} as any)
const OutboxSocialSentIndexRoute = OutboxSocialSentIndexRouteImport.update({
  id: '/sent/',
  path: '/sent/',
  getParentRoute: () => OutboxSocialRouteRoute,
} as any)
const OutboxSocialScheduleIndexRoute =
  OutboxSocialScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => OutboxSocialRouteRoute,
  } as any)
const OutboxSocialQueueIndexRoute = OutboxSocialQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => OutboxSocialRouteRoute,
} as any)
const OutboxSequencesSentIndexRoute =
  OutboxSequencesSentIndexRouteImport.update({
    id: '/sent/',
    path: '/sent/',
    getParentRoute: () => OutboxSequencesRouteRoute,
  } as any)
const OutboxSequencesQueueIndexRoute =
  OutboxSequencesQueueIndexRouteImport.update({
    id: '/queue/',
    path: '/queue/',
    getParentRoute: () => OutboxSequencesRouteRoute,
  } as any)
const OutboxSequencesActiveIndexRoute =
  OutboxSequencesActiveIndexRouteImport.update({
    id: '/active/',
    path: '/active/',
    getParentRoute: () => OutboxSequencesRouteRoute,
  } as any)
const OutboxNewsletterSentIndexRoute =
  OutboxNewsletterSentIndexRouteImport.update({
    id: '/sent/',
    path: '/sent/',
    getParentRoute: () => OutboxNewsletterRouteRoute,
  } as any)
const OutboxNewsletterScheduleIndexRoute =
  OutboxNewsletterScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => OutboxNewsletterRouteRoute,
  } as any)
const OutboxNewsletterQueueIndexRoute =
  OutboxNewsletterQueueIndexRouteImport.update({
    id: '/queue/',
    path: '/queue/',
    getParentRoute: () => OutboxNewsletterRouteRoute,
  } as any)
const OutboxEmailSentIndexRoute = OutboxEmailSentIndexRouteImport.update({
  id: '/sent/',
  path: '/sent/',
  getParentRoute: () => OutboxEmailRouteRoute,
} as any)
const OutboxEmailScheduleIndexRoute =
  OutboxEmailScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => OutboxEmailRouteRoute,
  } as any)
const OutboxEmailQueueIndexRoute = OutboxEmailQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => OutboxEmailRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/delegations': typeof DelegationsRouteRouteWithChildren
  '/email-queue': typeof EmailQueueRouteRouteWithChildren
  '/emails': typeof EmailsRouteRouteWithChildren
  '/finance': typeof FinanceRouteRouteWithChildren
  '/fundraising': typeof FundraisingRouteRouteWithChildren
  '/mail': typeof MailRouteRouteWithChildren
  '/outbox': typeof OutboxRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/storyboard': typeof StoryboardRouteRouteWithChildren
  '/video': typeof VideoRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/finance/transactions': typeof FinanceTransactionsRouteRouteWithChildren
  '/outbox/email': typeof OutboxEmailRouteRouteWithChildren
  '/outbox/newsletter': typeof OutboxNewsletterRouteRouteWithChildren
  '/outbox/sequences': typeof OutboxSequencesRouteRouteWithChildren
  '/outbox/social': typeof OutboxSocialRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/delegations/$id': typeof DelegationsIdRoute
  '/email-queue/$id': typeof EmailQueueIdRoute
  '/emails/$id': typeof EmailsIdRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/mail/$id': typeof MailIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/agent-runs/': typeof AgentRunsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/claude/': typeof ClaudeIndexRoute
  '/content/': typeof ContentIndexRoute
  '/cron/': typeof CronIndexRoute
  '/delegations/': typeof DelegationsIndexRoute
  '/email-queue/': typeof EmailQueueIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/fundraising/': typeof FundraisingIndexRoute
  '/handoffs/': typeof HandoffsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mail/': typeof MailIndexRoute
  '/outbox/': typeof OutboxIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storyboard/': typeof StoryboardIndexRoute
  '/strategy/': typeof StrategyIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/video/': typeof VideoIndexRoute
  '/finance/transactions/$id': typeof FinanceTransactionsIdRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/email-queue/approvals/': typeof EmailQueueApprovalsIndexRoute
  '/email-queue/replies/': typeof EmailQueueRepliesIndexRoute
  '/email-queue/sent/': typeof EmailQueueSentIndexRoute
  '/email-queue/sequences/': typeof EmailQueueSequencesIndexRoute
  '/emails/drafts/': typeof EmailsDraftsIndexRoute
  '/finance/inter-company/': typeof FinanceInterCompanyIndexRoute
  '/finance/receivables/': typeof FinanceReceivablesIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/fundraising/analytics/': typeof FundraisingAnalyticsIndexRoute
  '/fundraising/approvals/': typeof FundraisingApprovalsIndexRoute
  '/mail/all/': typeof MailAllIndexRoute
  '/mail/drafts/': typeof MailDraftsIndexRoute
  '/mail/inbox/': typeof MailInboxIndexRoute
  '/mail/triage/': typeof MailTriageIndexRoute
  '/outbox/email/': typeof OutboxEmailIndexRoute
  '/outbox/newsletter/': typeof OutboxNewsletterIndexRoute
  '/outbox/sent/': typeof OutboxSentIndexRoute
  '/outbox/sequences/': typeof OutboxSequencesIndexRoute
  '/outbox/social/': typeof OutboxSocialIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
  '/outbox/email/queue/': typeof OutboxEmailQueueIndexRoute
  '/outbox/email/schedule/': typeof OutboxEmailScheduleIndexRoute
  '/outbox/email/sent/': typeof OutboxEmailSentIndexRoute
  '/outbox/newsletter/queue/': typeof OutboxNewsletterQueueIndexRoute
  '/outbox/newsletter/schedule/': typeof OutboxNewsletterScheduleIndexRoute
  '/outbox/newsletter/sent/': typeof OutboxNewsletterSentIndexRoute
  '/outbox/sequences/active/': typeof OutboxSequencesActiveIndexRoute
  '/outbox/sequences/queue/': typeof OutboxSequencesQueueIndexRoute
  '/outbox/sequences/sent/': typeof OutboxSequencesSentIndexRoute
  '/outbox/social/queue/': typeof OutboxSocialQueueIndexRoute
  '/outbox/social/schedule/': typeof OutboxSocialScheduleIndexRoute
  '/outbox/social/sent/': typeof OutboxSocialSentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/finance/transactions': typeof FinanceTransactionsRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/delegations/$id': typeof DelegationsIdRoute
  '/email-queue/$id': typeof EmailQueueIdRoute
  '/emails/$id': typeof EmailsIdRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/mail/$id': typeof MailIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/agent-runs': typeof AgentRunsIndexRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/claude': typeof ClaudeIndexRoute
  '/content': typeof ContentIndexRoute
  '/cron': typeof CronIndexRoute
  '/delegations': typeof DelegationsIndexRoute
  '/email-queue': typeof EmailQueueIndexRoute
  '/emails': typeof EmailsIndexRoute
  '/executive': typeof ExecutiveIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/fundraising': typeof FundraisingIndexRoute
  '/handoffs': typeof HandoffsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/mail': typeof MailIndexRoute
  '/outbox': typeof OutboxIndexRoute
  '/partnerships': typeof PartnershipsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/storyboard': typeof StoryboardIndexRoute
  '/strategy': typeof StrategyIndexRoute
  '/triage': typeof TriageIndexRoute
  '/video': typeof VideoIndexRoute
  '/finance/transactions/$id': typeof FinanceTransactionsIdRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/email-queue/approvals': typeof EmailQueueApprovalsIndexRoute
  '/email-queue/replies': typeof EmailQueueRepliesIndexRoute
  '/email-queue/sent': typeof EmailQueueSentIndexRoute
  '/email-queue/sequences': typeof EmailQueueSequencesIndexRoute
  '/emails/drafts': typeof EmailsDraftsIndexRoute
  '/finance/inter-company': typeof FinanceInterCompanyIndexRoute
  '/finance/receivables': typeof FinanceReceivablesIndexRoute
  '/finance/reports': typeof FinanceReportsIndexRoute
  '/fundraising/analytics': typeof FundraisingAnalyticsIndexRoute
  '/fundraising/approvals': typeof FundraisingApprovalsIndexRoute
  '/mail/all': typeof MailAllIndexRoute
  '/mail/drafts': typeof MailDraftsIndexRoute
  '/mail/inbox': typeof MailInboxIndexRoute
  '/mail/triage': typeof MailTriageIndexRoute
  '/outbox/email': typeof OutboxEmailIndexRoute
  '/outbox/newsletter': typeof OutboxNewsletterIndexRoute
  '/outbox/sent': typeof OutboxSentIndexRoute
  '/outbox/sequences': typeof OutboxSequencesIndexRoute
  '/outbox/social': typeof OutboxSocialIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/sessions/all': typeof SessionsAllIndexRoute
  '/sessions/by-agent': typeof SessionsByAgentIndexRoute
  '/outbox/email/queue': typeof OutboxEmailQueueIndexRoute
  '/outbox/email/schedule': typeof OutboxEmailScheduleIndexRoute
  '/outbox/email/sent': typeof OutboxEmailSentIndexRoute
  '/outbox/newsletter/queue': typeof OutboxNewsletterQueueIndexRoute
  '/outbox/newsletter/schedule': typeof OutboxNewsletterScheduleIndexRoute
  '/outbox/newsletter/sent': typeof OutboxNewsletterSentIndexRoute
  '/outbox/sequences/active': typeof OutboxSequencesActiveIndexRoute
  '/outbox/sequences/queue': typeof OutboxSequencesQueueIndexRoute
  '/outbox/sequences/sent': typeof OutboxSequencesSentIndexRoute
  '/outbox/social/queue': typeof OutboxSocialQueueIndexRoute
  '/outbox/social/schedule': typeof OutboxSocialScheduleIndexRoute
  '/outbox/social/sent': typeof OutboxSocialSentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/delegations': typeof DelegationsRouteRouteWithChildren
  '/email-queue': typeof EmailQueueRouteRouteWithChildren
  '/emails': typeof EmailsRouteRouteWithChildren
  '/finance': typeof FinanceRouteRouteWithChildren
  '/fundraising': typeof FundraisingRouteRouteWithChildren
  '/mail': typeof MailRouteRouteWithChildren
  '/outbox': typeof OutboxRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/storyboard': typeof StoryboardRouteRouteWithChildren
  '/video': typeof VideoRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/finance/transactions': typeof FinanceTransactionsRouteRouteWithChildren
  '/outbox/email': typeof OutboxEmailRouteRouteWithChildren
  '/outbox/newsletter': typeof OutboxNewsletterRouteRouteWithChildren
  '/outbox/sequences': typeof OutboxSequencesRouteRouteWithChildren
  '/outbox/social': typeof OutboxSocialRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/delegations/$id': typeof DelegationsIdRoute
  '/email-queue/$id': typeof EmailQueueIdRoute
  '/emails/$id': typeof EmailsIdRoute
  '/handoffs/$id': typeof HandoffsIdRoute
  '/mail/$id': typeof MailIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/agent-runs/': typeof AgentRunsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/claude/': typeof ClaudeIndexRoute
  '/content/': typeof ContentIndexRoute
  '/cron/': typeof CronIndexRoute
  '/delegations/': typeof DelegationsIndexRoute
  '/email-queue/': typeof EmailQueueIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/executive/': typeof ExecutiveIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/fundraising/': typeof FundraisingIndexRoute
  '/handoffs/': typeof HandoffsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/mail/': typeof MailIndexRoute
  '/outbox/': typeof OutboxIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storyboard/': typeof StoryboardIndexRoute
  '/strategy/': typeof StrategyIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/video/': typeof VideoIndexRoute
  '/finance/transactions/$id': typeof FinanceTransactionsIdRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/email-queue/approvals/': typeof EmailQueueApprovalsIndexRoute
  '/email-queue/replies/': typeof EmailQueueRepliesIndexRoute
  '/email-queue/sent/': typeof EmailQueueSentIndexRoute
  '/email-queue/sequences/': typeof EmailQueueSequencesIndexRoute
  '/emails/drafts/': typeof EmailsDraftsIndexRoute
  '/finance/inter-company/': typeof FinanceInterCompanyIndexRoute
  '/finance/receivables/': typeof FinanceReceivablesIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/fundraising/analytics/': typeof FundraisingAnalyticsIndexRoute
  '/fundraising/approvals/': typeof FundraisingApprovalsIndexRoute
  '/mail/all/': typeof MailAllIndexRoute
  '/mail/drafts/': typeof MailDraftsIndexRoute
  '/mail/inbox/': typeof MailInboxIndexRoute
  '/mail/triage/': typeof MailTriageIndexRoute
  '/outbox/email/': typeof OutboxEmailIndexRoute
  '/outbox/newsletter/': typeof OutboxNewsletterIndexRoute
  '/outbox/sent/': typeof OutboxSentIndexRoute
  '/outbox/sequences/': typeof OutboxSequencesIndexRoute
  '/outbox/social/': typeof OutboxSocialIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
  '/outbox/email/queue/': typeof OutboxEmailQueueIndexRoute
  '/outbox/email/schedule/': typeof OutboxEmailScheduleIndexRoute
  '/outbox/email/sent/': typeof OutboxEmailSentIndexRoute
  '/outbox/newsletter/queue/': typeof OutboxNewsletterQueueIndexRoute
  '/outbox/newsletter/schedule/': typeof OutboxNewsletterScheduleIndexRoute
  '/outbox/newsletter/sent/': typeof OutboxNewsletterSentIndexRoute
  '/outbox/sequences/active/': typeof OutboxSequencesActiveIndexRoute
  '/outbox/sequences/queue/': typeof OutboxSequencesQueueIndexRoute
  '/outbox/sequences/sent/': typeof OutboxSequencesSentIndexRoute
  '/outbox/social/queue/': typeof OutboxSocialQueueIndexRoute
  '/outbox/social/schedule/': typeof OutboxSocialScheduleIndexRoute
  '/outbox/social/sent/': typeof OutboxSocialSentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude'
    | '/delegations'
    | '/email-queue'
    | '/emails'
    | '/finance'
    | '/fundraising'
    | '/mail'
    | '/outbox'
    | '/sessions'
    | '/storyboard'
    | '/video'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/finance/transactions'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sequences'
    | '/outbox/social'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/delegations/$id'
    | '/email-queue/$id'
    | '/emails/$id'
    | '/handoffs/$id'
    | '/mail/$id'
    | '/reports/$id'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/agent-runs/'
    | '/approvals/'
    | '/calendar/'
    | '/claude/'
    | '/content/'
    | '/cron/'
    | '/delegations/'
    | '/email-queue/'
    | '/emails/'
    | '/executive/'
    | '/features/'
    | '/finance/'
    | '/fundraising/'
    | '/handoffs/'
    | '/inbox/'
    | '/mail/'
    | '/outbox/'
    | '/partnerships/'
    | '/reports/'
    | '/sales/'
    | '/sessions/'
    | '/settings/'
    | '/storyboard/'
    | '/strategy/'
    | '/triage/'
    | '/video/'
    | '/finance/transactions/$id'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/email-queue/approvals/'
    | '/email-queue/replies/'
    | '/email-queue/sent/'
    | '/email-queue/sequences/'
    | '/emails/drafts/'
    | '/finance/inter-company/'
    | '/finance/receivables/'
    | '/finance/reports/'
    | '/fundraising/analytics/'
    | '/fundraising/approvals/'
    | '/mail/all/'
    | '/mail/drafts/'
    | '/mail/inbox/'
    | '/mail/triage/'
    | '/outbox/email/'
    | '/outbox/newsletter/'
    | '/outbox/sent/'
    | '/outbox/sequences/'
    | '/outbox/social/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
    | '/outbox/email/queue/'
    | '/outbox/email/schedule/'
    | '/outbox/email/sent/'
    | '/outbox/newsletter/queue/'
    | '/outbox/newsletter/schedule/'
    | '/outbox/newsletter/sent/'
    | '/outbox/sequences/active/'
    | '/outbox/sequences/queue/'
    | '/outbox/sequences/sent/'
    | '/outbox/social/queue/'
    | '/outbox/social/schedule/'
    | '/outbox/social/sent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/finance/transactions'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/delegations/$id'
    | '/email-queue/$id'
    | '/emails/$id'
    | '/handoffs/$id'
    | '/mail/$id'
    | '/reports/$id'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/agent-runs'
    | '/approvals'
    | '/calendar'
    | '/claude'
    | '/content'
    | '/cron'
    | '/delegations'
    | '/email-queue'
    | '/emails'
    | '/executive'
    | '/features'
    | '/finance'
    | '/fundraising'
    | '/handoffs'
    | '/inbox'
    | '/mail'
    | '/outbox'
    | '/partnerships'
    | '/reports'
    | '/sales'
    | '/sessions'
    | '/settings'
    | '/storyboard'
    | '/strategy'
    | '/triage'
    | '/video'
    | '/finance/transactions/$id'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/email-queue/approvals'
    | '/email-queue/replies'
    | '/email-queue/sent'
    | '/email-queue/sequences'
    | '/emails/drafts'
    | '/finance/inter-company'
    | '/finance/receivables'
    | '/finance/reports'
    | '/fundraising/analytics'
    | '/fundraising/approvals'
    | '/mail/all'
    | '/mail/drafts'
    | '/mail/inbox'
    | '/mail/triage'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sent'
    | '/outbox/sequences'
    | '/outbox/social'
    | '/sessions/$sessionId'
    | '/sessions/all'
    | '/sessions/by-agent'
    | '/outbox/email/queue'
    | '/outbox/email/schedule'
    | '/outbox/email/sent'
    | '/outbox/newsletter/queue'
    | '/outbox/newsletter/schedule'
    | '/outbox/newsletter/sent'
    | '/outbox/sequences/active'
    | '/outbox/sequences/queue'
    | '/outbox/sequences/sent'
    | '/outbox/social/queue'
    | '/outbox/social/schedule'
    | '/outbox/social/sent'
  id:
    | '__root__'
    | '/'
    | '/claude'
    | '/delegations'
    | '/email-queue'
    | '/emails'
    | '/finance'
    | '/fundraising'
    | '/mail'
    | '/outbox'
    | '/sessions'
    | '/storyboard'
    | '/video'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/finance/transactions'
    | '/outbox/email'
    | '/outbox/newsletter'
    | '/outbox/sequences'
    | '/outbox/social'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/delegations/$id'
    | '/email-queue/$id'
    | '/emails/$id'
    | '/handoffs/$id'
    | '/mail/$id'
    | '/reports/$id'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/agent-runs/'
    | '/approvals/'
    | '/calendar/'
    | '/claude/'
    | '/content/'
    | '/cron/'
    | '/delegations/'
    | '/email-queue/'
    | '/emails/'
    | '/executive/'
    | '/features/'
    | '/finance/'
    | '/fundraising/'
    | '/handoffs/'
    | '/inbox/'
    | '/mail/'
    | '/outbox/'
    | '/partnerships/'
    | '/reports/'
    | '/sales/'
    | '/sessions/'
    | '/settings/'
    | '/storyboard/'
    | '/strategy/'
    | '/triage/'
    | '/video/'
    | '/finance/transactions/$id'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/email-queue/approvals/'
    | '/email-queue/replies/'
    | '/email-queue/sent/'
    | '/email-queue/sequences/'
    | '/emails/drafts/'
    | '/finance/inter-company/'
    | '/finance/receivables/'
    | '/finance/reports/'
    | '/fundraising/analytics/'
    | '/fundraising/approvals/'
    | '/mail/all/'
    | '/mail/drafts/'
    | '/mail/inbox/'
    | '/mail/triage/'
    | '/outbox/email/'
    | '/outbox/newsletter/'
    | '/outbox/sent/'
    | '/outbox/sequences/'
    | '/outbox/social/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
    | '/outbox/email/queue/'
    | '/outbox/email/schedule/'
    | '/outbox/email/sent/'
    | '/outbox/newsletter/queue/'
    | '/outbox/newsletter/schedule/'
    | '/outbox/newsletter/sent/'
    | '/outbox/sequences/active/'
    | '/outbox/sequences/queue/'
    | '/outbox/sequences/sent/'
    | '/outbox/social/queue/'
    | '/outbox/social/schedule/'
    | '/outbox/social/sent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeRouteRoute: typeof ClaudeRouteRouteWithChildren
  DelegationsRouteRoute: typeof DelegationsRouteRouteWithChildren
  EmailQueueRouteRoute: typeof EmailQueueRouteRouteWithChildren
  EmailsRouteRoute: typeof EmailsRouteRouteWithChildren
  FinanceRouteRoute: typeof FinanceRouteRouteWithChildren
  FundraisingRouteRoute: typeof FundraisingRouteRouteWithChildren
  MailRouteRoute: typeof MailRouteRouteWithChildren
  OutboxRouteRoute: typeof OutboxRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  StoryboardRouteRoute: typeof StoryboardRouteRouteWithChildren
  VideoRouteRoute: typeof VideoRouteRouteWithChildren
  ClaudeAssetsSmokeRoute: typeof ClaudeAssetsSmokeRoute
  CronSmokeRoute: typeof CronSmokeRoute
  IframeMountSmokeRoute: typeof IframeMountSmokeRoute
  InstallRoute: typeof InstallRoute
  IykeSmokeRoute: typeof IykeSmokeRoute
  McpSmokeRoute: typeof McpSmokeRoute
  PermsSmokeRoute: typeof PermsSmokeRoute
  PkgKernelStatusRoute: typeof PkgKernelStatusRoute
  PkgSmokeRoute: typeof PkgSmokeRoute
  SettingsSmokeRoute: typeof SettingsSmokeRoute
  SpikeAclRoute: typeof SpikeAclRoute
  SweeperRoute: typeof SweeperRoute
  UiroutesSmokeRoute: typeof UiroutesSmokeRoute
  HandoffsIdRoute: typeof HandoffsIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  AgentRunsIndexRoute: typeof AgentRunsIndexRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  ContentIndexRoute: typeof ContentIndexRoute
  CronIndexRoute: typeof CronIndexRoute
  ExecutiveIndexRoute: typeof ExecutiveIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  HandoffsIndexRoute: typeof HandoffsIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  PartnershipsIndexRoute: typeof PartnershipsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StrategyIndexRoute: typeof StrategyIndexRoute
  TriageIndexRoute: typeof TriageIndexRoute
  PkgPkgIdSplatRoute: typeof PkgPkgIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uiroutes-smoke': {
      id: '/uiroutes-smoke'
      path: '/uiroutes-smoke'
      fullPath: '/uiroutes-smoke'
      preLoaderRoute: typeof UiroutesSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweeper': {
      id: '/sweeper'
      path: '/sweeper'
      fullPath: '/sweeper'
      preLoaderRoute: typeof SweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike-acl': {
      id: '/spike-acl'
      path: '/spike-acl'
      fullPath: '/spike-acl'
      preLoaderRoute: typeof SpikeAclRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-smoke': {
      id: '/settings-smoke'
      path: '/settings-smoke'
      fullPath: '/settings-smoke'
      preLoaderRoute: typeof SettingsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-smoke': {
      id: '/pkg-smoke'
      path: '/pkg-smoke'
      fullPath: '/pkg-smoke'
      preLoaderRoute: typeof PkgSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-kernel-status': {
      id: '/pkg-kernel-status'
      path: '/pkg-kernel-status'
      fullPath: '/pkg-kernel-status'
      preLoaderRoute: typeof PkgKernelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perms-smoke': {
      id: '/perms-smoke'
      path: '/perms-smoke'
      fullPath: '/perms-smoke'
      preLoaderRoute: typeof PermsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-smoke': {
      id: '/mcp-smoke'
      path: '/mcp-smoke'
      fullPath: '/mcp-smoke'
      preLoaderRoute: typeof McpSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iyke-smoke': {
      id: '/iyke-smoke'
      path: '/iyke-smoke'
      fullPath: '/iyke-smoke'
      preLoaderRoute: typeof IykeSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-mount-smoke': {
      id: '/iframe-mount-smoke'
      path: '/iframe-mount-smoke'
      fullPath: '/iframe-mount-smoke'
      preLoaderRoute: typeof IframeMountSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-smoke': {
      id: '/cron-smoke'
      path: '/cron-smoke'
      fullPath: '/cron-smoke'
      preLoaderRoute: typeof CronSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-assets-smoke': {
      id: '/claude-assets-smoke'
      path: '/claude-assets-smoke'
      fullPath: '/claude-assets-smoke'
      preLoaderRoute: typeof ClaudeAssetsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox': {
      id: '/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof OutboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-queue': {
      id: '/email-queue'
      path: '/email-queue'
      fullPath: '/email-queue'
      preLoaderRoute: typeof EmailQueueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegations': {
      id: '/delegations'
      path: '/delegations'
      fullPath: '/delegations'
      preLoaderRoute: typeof DelegationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/triage/': {
      id: '/triage/'
      path: '/triage'
      fullPath: '/triage/'
      preLoaderRoute: typeof TriageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/': {
      id: '/strategy/'
      path: '/strategy'
      fullPath: '/strategy/'
      preLoaderRoute: typeof StrategyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard/': {
      id: '/storyboard/'
      path: '/'
      fullPath: '/storyboard/'
      preLoaderRoute: typeof StoryboardIndexRouteImport
      parentRoute: typeof StoryboardRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships/': {
      id: '/partnerships/'
      path: '/partnerships'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox/': {
      id: '/outbox/'
      path: '/'
      fullPath: '/outbox/'
      preLoaderRoute: typeof OutboxIndexRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/mail/': {
      id: '/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs/': {
      id: '/handoffs/'
      path: '/handoffs'
      fullPath: '/handoffs/'
      preLoaderRoute: typeof HandoffsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/': {
      id: '/fundraising/'
      path: '/'
      fullPath: '/fundraising/'
      preLoaderRoute: typeof FundraisingIndexRouteImport
      parentRoute: typeof FundraisingRouteRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/': {
      id: '/executive/'
      path: '/executive'
      fullPath: '/executive/'
      preLoaderRoute: typeof ExecutiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/': {
      id: '/emails/'
      path: '/'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/email-queue/': {
      id: '/email-queue/'
      path: '/'
      fullPath: '/email-queue/'
      preLoaderRoute: typeof EmailQueueIndexRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/delegations/': {
      id: '/delegations/'
      path: '/'
      fullPath: '/delegations/'
      preLoaderRoute: typeof DelegationsIndexRouteImport
      parentRoute: typeof DelegationsRouteRoute
    }
    '/cron/': {
      id: '/cron/'
      path: '/cron'
      fullPath: '/cron/'
      preLoaderRoute: typeof CronIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude/': {
      id: '/claude/'
      path: '/'
      fullPath: '/claude/'
      preLoaderRoute: typeof ClaudeIndexRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs/': {
      id: '/agent-runs/'
      path: '/agent-runs'
      fullPath: '/agent-runs/'
      preLoaderRoute: typeof AgentRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/queue': {
      id: '/video/queue'
      path: '/queue'
      fullPath: '/video/queue'
      preLoaderRoute: typeof VideoQueueRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/video/$compositionId': {
      id: '/video/$compositionId'
      path: '/$compositionId'
      fullPath: '/video/$compositionId'
      preLoaderRoute: typeof VideoCompositionIdRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/storyboard/$id': {
      id: '/storyboard/$id'
      path: '/$id'
      fullPath: '/storyboard/$id'
      preLoaderRoute: typeof StoryboardIdRouteImport
      parentRoute: typeof StoryboardRouteRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$id': {
      id: '/mail/$id'
      path: '/$id'
      fullPath: '/mail/$id'
      preLoaderRoute: typeof MailIdRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/handoffs/$id': {
      id: '/handoffs/$id'
      path: '/handoffs/$id'
      fullPath: '/handoffs/$id'
      preLoaderRoute: typeof HandoffsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$id': {
      id: '/emails/$id'
      path: '/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof EmailsIdRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/email-queue/$id': {
      id: '/email-queue/$id'
      path: '/$id'
      fullPath: '/email-queue/$id'
      preLoaderRoute: typeof EmailQueueIdRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/delegations/$id': {
      id: '/delegations/$id'
      path: '/$id'
      fullPath: '/delegations/$id'
      preLoaderRoute: typeof DelegationsIdRouteImport
      parentRoute: typeof DelegationsRouteRoute
    }
    '/claude/skills': {
      id: '/claude/skills'
      path: '/skills'
      fullPath: '/claude/skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/mcps': {
      id: '/claude/mcps'
      path: '/mcps'
      fullPath: '/claude/mcps'
      preLoaderRoute: typeof ClaudeMcpsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/hooks': {
      id: '/claude/hooks'
      path: '/hooks'
      fullPath: '/claude/hooks'
      preLoaderRoute: typeof ClaudeHooksRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/commands': {
      id: '/claude/commands'
      path: '/commands'
      fullPath: '/claude/commands'
      preLoaderRoute: typeof ClaudeCommandsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/outbox/social': {
      id: '/outbox/social'
      path: '/social'
      fullPath: '/outbox/social'
      preLoaderRoute: typeof OutboxSocialRouteRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/sequences': {
      id: '/outbox/sequences'
      path: '/sequences'
      fullPath: '/outbox/sequences'
      preLoaderRoute: typeof OutboxSequencesRouteRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/newsletter': {
      id: '/outbox/newsletter'
      path: '/newsletter'
      fullPath: '/outbox/newsletter'
      preLoaderRoute: typeof OutboxNewsletterRouteRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/email': {
      id: '/outbox/email'
      path: '/email'
      fullPath: '/outbox/email'
      preLoaderRoute: typeof OutboxEmailRouteRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/sessions/by-agent/': {
      id: '/sessions/by-agent/'
      path: '/by-agent'
      fullPath: '/sessions/by-agent/'
      preLoaderRoute: typeof SessionsByAgentIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/all/': {
      id: '/sessions/all/'
      path: '/all'
      fullPath: '/sessions/all/'
      preLoaderRoute: typeof SessionsAllIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/outbox/social/': {
      id: '/outbox/social/'
      path: '/'
      fullPath: '/outbox/social/'
      preLoaderRoute: typeof OutboxSocialIndexRouteImport
      parentRoute: typeof OutboxSocialRouteRoute
    }
    '/outbox/sequences/': {
      id: '/outbox/sequences/'
      path: '/'
      fullPath: '/outbox/sequences/'
      preLoaderRoute: typeof OutboxSequencesIndexRouteImport
      parentRoute: typeof OutboxSequencesRouteRoute
    }
    '/outbox/sent/': {
      id: '/outbox/sent/'
      path: '/sent'
      fullPath: '/outbox/sent/'
      preLoaderRoute: typeof OutboxSentIndexRouteImport
      parentRoute: typeof OutboxRouteRoute
    }
    '/outbox/newsletter/': {
      id: '/outbox/newsletter/'
      path: '/'
      fullPath: '/outbox/newsletter/'
      preLoaderRoute: typeof OutboxNewsletterIndexRouteImport
      parentRoute: typeof OutboxNewsletterRouteRoute
    }
    '/outbox/email/': {
      id: '/outbox/email/'
      path: '/'
      fullPath: '/outbox/email/'
      preLoaderRoute: typeof OutboxEmailIndexRouteImport
      parentRoute: typeof OutboxEmailRouteRoute
    }
    '/mail/triage/': {
      id: '/mail/triage/'
      path: '/triage'
      fullPath: '/mail/triage/'
      preLoaderRoute: typeof MailTriageIndexRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/mail/inbox/': {
      id: '/mail/inbox/'
      path: '/inbox'
      fullPath: '/mail/inbox/'
      preLoaderRoute: typeof MailInboxIndexRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/mail/drafts/': {
      id: '/mail/drafts/'
      path: '/drafts'
      fullPath: '/mail/drafts/'
      preLoaderRoute: typeof MailDraftsIndexRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/mail/all/': {
      id: '/mail/all/'
      path: '/all'
      fullPath: '/mail/all/'
      preLoaderRoute: typeof MailAllIndexRouteImport
      parentRoute: typeof MailRouteRoute
    }
    '/fundraising/approvals/': {
      id: '/fundraising/approvals/'
      path: '/approvals'
      fullPath: '/fundraising/approvals/'
      preLoaderRoute: typeof FundraisingApprovalsIndexRouteImport
      parentRoute: typeof FundraisingRouteRoute
    }
    '/fundraising/analytics/': {
      id: '/fundraising/analytics/'
      path: '/analytics'
      fullPath: '/fundraising/analytics/'
      preLoaderRoute: typeof FundraisingAnalyticsIndexRouteImport
      parentRoute: typeof FundraisingRouteRoute
    }
    '/finance/reports/': {
      id: '/finance/reports/'
      path: '/reports'
      fullPath: '/finance/reports/'
      preLoaderRoute: typeof FinanceReportsIndexRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/finance/receivables/': {
      id: '/finance/receivables/'
      path: '/receivables'
      fullPath: '/finance/receivables/'
      preLoaderRoute: typeof FinanceReceivablesIndexRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/finance/inter-company/': {
      id: '/finance/inter-company/'
      path: '/inter-company'
      fullPath: '/finance/inter-company/'
      preLoaderRoute: typeof FinanceInterCompanyIndexRouteImport
      parentRoute: typeof FinanceRouteRoute
    }
    '/emails/drafts/': {
      id: '/emails/drafts/'
      path: '/drafts'
      fullPath: '/emails/drafts/'
      preLoaderRoute: typeof EmailsDraftsIndexRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/email-queue/sequences/': {
      id: '/email-queue/sequences/'
      path: '/sequences'
      fullPath: '/email-queue/sequences/'
      preLoaderRoute: typeof EmailQueueSequencesIndexRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/email-queue/sent/': {
      id: '/email-queue/sent/'
      path: '/sent'
      fullPath: '/email-queue/sent/'
      preLoaderRoute: typeof EmailQueueSentIndexRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/email-queue/replies/': {
      id: '/email-queue/replies/'
      path: '/replies'
      fullPath: '/email-queue/replies/'
      preLoaderRoute: typeof EmailQueueRepliesIndexRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/email-queue/approvals/': {
      id: '/email-queue/approvals/'
      path: '/approvals'
      fullPath: '/email-queue/approvals/'
      preLoaderRoute: typeof EmailQueueApprovalsIndexRouteImport
      parentRoute: typeof EmailQueueRouteRoute
    }
    '/sessions/by-agent/$agent': {
      id: '/sessions/by-agent/$agent'
      path: '/by-agent/$agent'
      fullPath: '/sessions/by-agent/$agent'
      preLoaderRoute: typeof SessionsByAgentAgentRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/pkg/$pkgId/$': {
      id: '/pkg/$pkgId/$'
      path: '/pkg/$pkgId/$'
      fullPath: '/pkg/$pkgId/$'
      preLoaderRoute: typeof PkgPkgIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions/$id': {
      id: '/finance/transactions/$id'
      path: '/$id'
      fullPath: '/finance/transactions/$id'
      preLoaderRoute: typeof FinanceTransactionsIdRouteImport
      parentRoute: typeof FinanceTransactionsRouteRoute
    }
    '/outbox/social/sent/': {
      id: '/outbox/social/sent/'
      path: '/sent'
      fullPath: '/outbox/social/sent/'
      preLoaderRoute: typeof OutboxSocialSentIndexRouteImport
      parentRoute: typeof OutboxSocialRouteRoute
    }
    '/outbox/social/schedule/': {
      id: '/outbox/social/schedule/'
      path: '/schedule'
      fullPath: '/outbox/social/schedule/'
      preLoaderRoute: typeof OutboxSocialScheduleIndexRouteImport
      parentRoute: typeof OutboxSocialRouteRoute
    }
    '/outbox/social/queue/': {
      id: '/outbox/social/queue/'
      path: '/queue'
      fullPath: '/outbox/social/queue/'
      preLoaderRoute: typeof OutboxSocialQueueIndexRouteImport
      parentRoute: typeof OutboxSocialRouteRoute
    }
    '/outbox/sequences/sent/': {
      id: '/outbox/sequences/sent/'
      path: '/sent'
      fullPath: '/outbox/sequences/sent/'
      preLoaderRoute: typeof OutboxSequencesSentIndexRouteImport
      parentRoute: typeof OutboxSequencesRouteRoute
    }
    '/outbox/sequences/queue/': {
      id: '/outbox/sequences/queue/'
      path: '/queue'
      fullPath: '/outbox/sequences/queue/'
      preLoaderRoute: typeof OutboxSequencesQueueIndexRouteImport
      parentRoute: typeof OutboxSequencesRouteRoute
    }
    '/outbox/sequences/active/': {
      id: '/outbox/sequences/active/'
      path: '/active'
      fullPath: '/outbox/sequences/active/'
      preLoaderRoute: typeof OutboxSequencesActiveIndexRouteImport
      parentRoute: typeof OutboxSequencesRouteRoute
    }
    '/outbox/newsletter/sent/': {
      id: '/outbox/newsletter/sent/'
      path: '/sent'
      fullPath: '/outbox/newsletter/sent/'
      preLoaderRoute: typeof OutboxNewsletterSentIndexRouteImport
      parentRoute: typeof OutboxNewsletterRouteRoute
    }
    '/outbox/newsletter/schedule/': {
      id: '/outbox/newsletter/schedule/'
      path: '/schedule'
      fullPath: '/outbox/newsletter/schedule/'
      preLoaderRoute: typeof OutboxNewsletterScheduleIndexRouteImport
      parentRoute: typeof OutboxNewsletterRouteRoute
    }
    '/outbox/newsletter/queue/': {
      id: '/outbox/newsletter/queue/'
      path: '/queue'
      fullPath: '/outbox/newsletter/queue/'
      preLoaderRoute: typeof OutboxNewsletterQueueIndexRouteImport
      parentRoute: typeof OutboxNewsletterRouteRoute
    }
    '/outbox/email/sent/': {
      id: '/outbox/email/sent/'
      path: '/sent'
      fullPath: '/outbox/email/sent/'
      preLoaderRoute: typeof OutboxEmailSentIndexRouteImport
      parentRoute: typeof OutboxEmailRouteRoute
    }
    '/outbox/email/schedule/': {
      id: '/outbox/email/schedule/'
      path: '/schedule'
      fullPath: '/outbox/email/schedule/'
      preLoaderRoute: typeof OutboxEmailScheduleIndexRouteImport
      parentRoute: typeof OutboxEmailRouteRoute
    }
    '/outbox/email/queue/': {
      id: '/outbox/email/queue/'
      path: '/queue'
      fullPath: '/outbox/email/queue/'
      preLoaderRoute: typeof OutboxEmailQueueIndexRouteImport
      parentRoute: typeof OutboxEmailRouteRoute
    }
  }
}

interface ClaudeRouteRouteChildren {
  ClaudeCommandsRoute: typeof ClaudeCommandsRoute
  ClaudeHooksRoute: typeof ClaudeHooksRoute
  ClaudeMcpsRoute: typeof ClaudeMcpsRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  ClaudeIndexRoute: typeof ClaudeIndexRoute
}

const ClaudeRouteRouteChildren: ClaudeRouteRouteChildren = {
  ClaudeCommandsRoute: ClaudeCommandsRoute,
  ClaudeHooksRoute: ClaudeHooksRoute,
  ClaudeMcpsRoute: ClaudeMcpsRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  ClaudeIndexRoute: ClaudeIndexRoute,
}

const ClaudeRouteRouteWithChildren = ClaudeRouteRoute._addFileChildren(
  ClaudeRouteRouteChildren,
)

interface DelegationsRouteRouteChildren {
  DelegationsIdRoute: typeof DelegationsIdRoute
  DelegationsIndexRoute: typeof DelegationsIndexRoute
}

const DelegationsRouteRouteChildren: DelegationsRouteRouteChildren = {
  DelegationsIdRoute: DelegationsIdRoute,
  DelegationsIndexRoute: DelegationsIndexRoute,
}

const DelegationsRouteRouteWithChildren =
  DelegationsRouteRoute._addFileChildren(DelegationsRouteRouteChildren)

interface EmailQueueRouteRouteChildren {
  EmailQueueIdRoute: typeof EmailQueueIdRoute
  EmailQueueIndexRoute: typeof EmailQueueIndexRoute
  EmailQueueApprovalsIndexRoute: typeof EmailQueueApprovalsIndexRoute
  EmailQueueRepliesIndexRoute: typeof EmailQueueRepliesIndexRoute
  EmailQueueSentIndexRoute: typeof EmailQueueSentIndexRoute
  EmailQueueSequencesIndexRoute: typeof EmailQueueSequencesIndexRoute
}

const EmailQueueRouteRouteChildren: EmailQueueRouteRouteChildren = {
  EmailQueueIdRoute: EmailQueueIdRoute,
  EmailQueueIndexRoute: EmailQueueIndexRoute,
  EmailQueueApprovalsIndexRoute: EmailQueueApprovalsIndexRoute,
  EmailQueueRepliesIndexRoute: EmailQueueRepliesIndexRoute,
  EmailQueueSentIndexRoute: EmailQueueSentIndexRoute,
  EmailQueueSequencesIndexRoute: EmailQueueSequencesIndexRoute,
}

const EmailQueueRouteRouteWithChildren = EmailQueueRouteRoute._addFileChildren(
  EmailQueueRouteRouteChildren,
)

interface EmailsRouteRouteChildren {
  EmailsIdRoute: typeof EmailsIdRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
  EmailsDraftsIndexRoute: typeof EmailsDraftsIndexRoute
}

const EmailsRouteRouteChildren: EmailsRouteRouteChildren = {
  EmailsIdRoute: EmailsIdRoute,
  EmailsIndexRoute: EmailsIndexRoute,
  EmailsDraftsIndexRoute: EmailsDraftsIndexRoute,
}

const EmailsRouteRouteWithChildren = EmailsRouteRoute._addFileChildren(
  EmailsRouteRouteChildren,
)

interface FinanceTransactionsRouteRouteChildren {
  FinanceTransactionsIdRoute: typeof FinanceTransactionsIdRoute
}

const FinanceTransactionsRouteRouteChildren: FinanceTransactionsRouteRouteChildren =
  {
    FinanceTransactionsIdRoute: FinanceTransactionsIdRoute,
  }

const FinanceTransactionsRouteRouteWithChildren =
  FinanceTransactionsRouteRoute._addFileChildren(
    FinanceTransactionsRouteRouteChildren,
  )

interface FinanceRouteRouteChildren {
  FinanceTransactionsRouteRoute: typeof FinanceTransactionsRouteRouteWithChildren
  FinanceIndexRoute: typeof FinanceIndexRoute
  FinanceInterCompanyIndexRoute: typeof FinanceInterCompanyIndexRoute
  FinanceReceivablesIndexRoute: typeof FinanceReceivablesIndexRoute
  FinanceReportsIndexRoute: typeof FinanceReportsIndexRoute
}

const FinanceRouteRouteChildren: FinanceRouteRouteChildren = {
  FinanceTransactionsRouteRoute: FinanceTransactionsRouteRouteWithChildren,
  FinanceIndexRoute: FinanceIndexRoute,
  FinanceInterCompanyIndexRoute: FinanceInterCompanyIndexRoute,
  FinanceReceivablesIndexRoute: FinanceReceivablesIndexRoute,
  FinanceReportsIndexRoute: FinanceReportsIndexRoute,
}

const FinanceRouteRouteWithChildren = FinanceRouteRoute._addFileChildren(
  FinanceRouteRouteChildren,
)

interface FundraisingRouteRouteChildren {
  FundraisingIndexRoute: typeof FundraisingIndexRoute
  FundraisingAnalyticsIndexRoute: typeof FundraisingAnalyticsIndexRoute
  FundraisingApprovalsIndexRoute: typeof FundraisingApprovalsIndexRoute
}

const FundraisingRouteRouteChildren: FundraisingRouteRouteChildren = {
  FundraisingIndexRoute: FundraisingIndexRoute,
  FundraisingAnalyticsIndexRoute: FundraisingAnalyticsIndexRoute,
  FundraisingApprovalsIndexRoute: FundraisingApprovalsIndexRoute,
}

const FundraisingRouteRouteWithChildren =
  FundraisingRouteRoute._addFileChildren(FundraisingRouteRouteChildren)

interface MailRouteRouteChildren {
  MailIdRoute: typeof MailIdRoute
  MailIndexRoute: typeof MailIndexRoute
  MailAllIndexRoute: typeof MailAllIndexRoute
  MailDraftsIndexRoute: typeof MailDraftsIndexRoute
  MailInboxIndexRoute: typeof MailInboxIndexRoute
  MailTriageIndexRoute: typeof MailTriageIndexRoute
}

const MailRouteRouteChildren: MailRouteRouteChildren = {
  MailIdRoute: MailIdRoute,
  MailIndexRoute: MailIndexRoute,
  MailAllIndexRoute: MailAllIndexRoute,
  MailDraftsIndexRoute: MailDraftsIndexRoute,
  MailInboxIndexRoute: MailInboxIndexRoute,
  MailTriageIndexRoute: MailTriageIndexRoute,
}

const MailRouteRouteWithChildren = MailRouteRoute._addFileChildren(
  MailRouteRouteChildren,
)

interface OutboxEmailRouteRouteChildren {
  OutboxEmailIndexRoute: typeof OutboxEmailIndexRoute
  OutboxEmailQueueIndexRoute: typeof OutboxEmailQueueIndexRoute
  OutboxEmailScheduleIndexRoute: typeof OutboxEmailScheduleIndexRoute
  OutboxEmailSentIndexRoute: typeof OutboxEmailSentIndexRoute
}

const OutboxEmailRouteRouteChildren: OutboxEmailRouteRouteChildren = {
  OutboxEmailIndexRoute: OutboxEmailIndexRoute,
  OutboxEmailQueueIndexRoute: OutboxEmailQueueIndexRoute,
  OutboxEmailScheduleIndexRoute: OutboxEmailScheduleIndexRoute,
  OutboxEmailSentIndexRoute: OutboxEmailSentIndexRoute,
}

const OutboxEmailRouteRouteWithChildren =
  OutboxEmailRouteRoute._addFileChildren(OutboxEmailRouteRouteChildren)

interface OutboxNewsletterRouteRouteChildren {
  OutboxNewsletterIndexRoute: typeof OutboxNewsletterIndexRoute
  OutboxNewsletterQueueIndexRoute: typeof OutboxNewsletterQueueIndexRoute
  OutboxNewsletterScheduleIndexRoute: typeof OutboxNewsletterScheduleIndexRoute
  OutboxNewsletterSentIndexRoute: typeof OutboxNewsletterSentIndexRoute
}

const OutboxNewsletterRouteRouteChildren: OutboxNewsletterRouteRouteChildren = {
  OutboxNewsletterIndexRoute: OutboxNewsletterIndexRoute,
  OutboxNewsletterQueueIndexRoute: OutboxNewsletterQueueIndexRoute,
  OutboxNewsletterScheduleIndexRoute: OutboxNewsletterScheduleIndexRoute,
  OutboxNewsletterSentIndexRoute: OutboxNewsletterSentIndexRoute,
}

const OutboxNewsletterRouteRouteWithChildren =
  OutboxNewsletterRouteRoute._addFileChildren(
    OutboxNewsletterRouteRouteChildren,
  )

interface OutboxSequencesRouteRouteChildren {
  OutboxSequencesIndexRoute: typeof OutboxSequencesIndexRoute
  OutboxSequencesActiveIndexRoute: typeof OutboxSequencesActiveIndexRoute
  OutboxSequencesQueueIndexRoute: typeof OutboxSequencesQueueIndexRoute
  OutboxSequencesSentIndexRoute: typeof OutboxSequencesSentIndexRoute
}

const OutboxSequencesRouteRouteChildren: OutboxSequencesRouteRouteChildren = {
  OutboxSequencesIndexRoute: OutboxSequencesIndexRoute,
  OutboxSequencesActiveIndexRoute: OutboxSequencesActiveIndexRoute,
  OutboxSequencesQueueIndexRoute: OutboxSequencesQueueIndexRoute,
  OutboxSequencesSentIndexRoute: OutboxSequencesSentIndexRoute,
}

const OutboxSequencesRouteRouteWithChildren =
  OutboxSequencesRouteRoute._addFileChildren(OutboxSequencesRouteRouteChildren)

interface OutboxSocialRouteRouteChildren {
  OutboxSocialIndexRoute: typeof OutboxSocialIndexRoute
  OutboxSocialQueueIndexRoute: typeof OutboxSocialQueueIndexRoute
  OutboxSocialScheduleIndexRoute: typeof OutboxSocialScheduleIndexRoute
  OutboxSocialSentIndexRoute: typeof OutboxSocialSentIndexRoute
}

const OutboxSocialRouteRouteChildren: OutboxSocialRouteRouteChildren = {
  OutboxSocialIndexRoute: OutboxSocialIndexRoute,
  OutboxSocialQueueIndexRoute: OutboxSocialQueueIndexRoute,
  OutboxSocialScheduleIndexRoute: OutboxSocialScheduleIndexRoute,
  OutboxSocialSentIndexRoute: OutboxSocialSentIndexRoute,
}

const OutboxSocialRouteRouteWithChildren =
  OutboxSocialRouteRoute._addFileChildren(OutboxSocialRouteRouteChildren)

interface OutboxRouteRouteChildren {
  OutboxEmailRouteRoute: typeof OutboxEmailRouteRouteWithChildren
  OutboxNewsletterRouteRoute: typeof OutboxNewsletterRouteRouteWithChildren
  OutboxSequencesRouteRoute: typeof OutboxSequencesRouteRouteWithChildren
  OutboxSocialRouteRoute: typeof OutboxSocialRouteRouteWithChildren
  OutboxIndexRoute: typeof OutboxIndexRoute
  OutboxSentIndexRoute: typeof OutboxSentIndexRoute
}

const OutboxRouteRouteChildren: OutboxRouteRouteChildren = {
  OutboxEmailRouteRoute: OutboxEmailRouteRouteWithChildren,
  OutboxNewsletterRouteRoute: OutboxNewsletterRouteRouteWithChildren,
  OutboxSequencesRouteRoute: OutboxSequencesRouteRouteWithChildren,
  OutboxSocialRouteRoute: OutboxSocialRouteRouteWithChildren,
  OutboxIndexRoute: OutboxIndexRoute,
  OutboxSentIndexRoute: OutboxSentIndexRoute,
}

const OutboxRouteRouteWithChildren = OutboxRouteRoute._addFileChildren(
  OutboxRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsByAgentAgentRoute: typeof SessionsByAgentAgentRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  SessionsAllIndexRoute: typeof SessionsAllIndexRoute
  SessionsByAgentIndexRoute: typeof SessionsByAgentIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsByAgentAgentRoute: SessionsByAgentAgentRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  SessionsAllIndexRoute: SessionsAllIndexRoute,
  SessionsByAgentIndexRoute: SessionsByAgentIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

interface StoryboardRouteRouteChildren {
  StoryboardIdRoute: typeof StoryboardIdRoute
  StoryboardIndexRoute: typeof StoryboardIndexRoute
}

const StoryboardRouteRouteChildren: StoryboardRouteRouteChildren = {
  StoryboardIdRoute: StoryboardIdRoute,
  StoryboardIndexRoute: StoryboardIndexRoute,
}

const StoryboardRouteRouteWithChildren = StoryboardRouteRoute._addFileChildren(
  StoryboardRouteRouteChildren,
)

interface VideoRouteRouteChildren {
  VideoCompositionIdRoute: typeof VideoCompositionIdRoute
  VideoQueueRoute: typeof VideoQueueRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

const VideoRouteRouteChildren: VideoRouteRouteChildren = {
  VideoCompositionIdRoute: VideoCompositionIdRoute,
  VideoQueueRoute: VideoQueueRoute,
  VideoIndexRoute: VideoIndexRoute,
}

const VideoRouteRouteWithChildren = VideoRouteRoute._addFileChildren(
  VideoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeRouteRoute: ClaudeRouteRouteWithChildren,
  DelegationsRouteRoute: DelegationsRouteRouteWithChildren,
  EmailQueueRouteRoute: EmailQueueRouteRouteWithChildren,
  EmailsRouteRoute: EmailsRouteRouteWithChildren,
  FinanceRouteRoute: FinanceRouteRouteWithChildren,
  FundraisingRouteRoute: FundraisingRouteRouteWithChildren,
  MailRouteRoute: MailRouteRouteWithChildren,
  OutboxRouteRoute: OutboxRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  StoryboardRouteRoute: StoryboardRouteRouteWithChildren,
  VideoRouteRoute: VideoRouteRouteWithChildren,
  ClaudeAssetsSmokeRoute: ClaudeAssetsSmokeRoute,
  CronSmokeRoute: CronSmokeRoute,
  IframeMountSmokeRoute: IframeMountSmokeRoute,
  InstallRoute: InstallRoute,
  IykeSmokeRoute: IykeSmokeRoute,
  McpSmokeRoute: McpSmokeRoute,
  PermsSmokeRoute: PermsSmokeRoute,
  PkgKernelStatusRoute: PkgKernelStatusRoute,
  PkgSmokeRoute: PkgSmokeRoute,
  SettingsSmokeRoute: SettingsSmokeRoute,
  SpikeAclRoute: SpikeAclRoute,
  SweeperRoute: SweeperRoute,
  UiroutesSmokeRoute: UiroutesSmokeRoute,
  HandoffsIdRoute: HandoffsIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  AgentRunsIndexRoute: AgentRunsIndexRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  ContentIndexRoute: ContentIndexRoute,
  CronIndexRoute: CronIndexRoute,
  ExecutiveIndexRoute: ExecutiveIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  HandoffsIndexRoute: HandoffsIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  PartnershipsIndexRoute: PartnershipsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StrategyIndexRoute: StrategyIndexRoute,
  TriageIndexRoute: TriageIndexRoute,
  PkgPkgIdSplatRoute: PkgPkgIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
