/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiroutesSmokeRouteImport } from './routes/uiroutes-smoke'
import { Route as SweeperRouteImport } from './routes/sweeper'
import { Route as SpikeAclRouteImport } from './routes/spike-acl'
import { Route as SettingsSmokeRouteImport } from './routes/settings-smoke'
import { Route as PkgSmokeRouteImport } from './routes/pkg-smoke'
import { Route as PkgKernelStatusRouteImport } from './routes/pkg-kernel-status'
import { Route as PermsSmokeRouteImport } from './routes/perms-smoke'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as McpSmokeRouteImport } from './routes/mcp-smoke'
import { Route as IykeSmokeRouteImport } from './routes/iyke-smoke'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IframeMountSmokeRouteImport } from './routes/iframe-mount-smoke'
import { Route as CronSmokeRouteImport } from './routes/cron-smoke'
import { Route as ClaudeAssetsSmokeRouteImport } from './routes/claude-assets-smoke'
import { Route as VideoRouteRouteImport } from './routes/video/route'
import { Route as StoryboardRouteRouteImport } from './routes/storyboard/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as EmailsRouteRouteImport } from './routes/emails/route'
import { Route as ClaudeRouteRouteImport } from './routes/claude/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video/index'
import { Route as TriageIndexRouteImport } from './routes/triage/index'
import { Route as StoryboardIndexRouteImport } from './routes/storyboard/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as EmailsIndexRouteImport } from './routes/emails/index'
import { Route as ClaudeIndexRouteImport } from './routes/claude/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as VideoQueueRouteImport } from './routes/video/queue'
import { Route as VideoCompositionIdRouteImport } from './routes/video/$compositionId'
import { Route as StoryboardIdRouteImport } from './routes/storyboard/$id'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as EmailsIdRouteImport } from './routes/emails/$id'
import { Route as ClaudeSkillsRouteImport } from './routes/claude/skills'
import { Route as ClaudeMcpsRouteImport } from './routes/claude/mcps'
import { Route as ClaudeHooksRouteImport } from './routes/claude/hooks'
import { Route as ClaudeCommandsRouteImport } from './routes/claude/commands'
import { Route as PkgPkgIdRouteRouteImport } from './routes/pkg/$pkgId/route'
import { Route as SessionsByAgentIndexRouteImport } from './routes/sessions/by-agent/index'
import { Route as SessionsAllIndexRouteImport } from './routes/sessions/all/index'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as EmailsDraftsIndexRouteImport } from './routes/emails/drafts/index'
import { Route as SessionsByAgentAgentRouteImport } from './routes/sessions/by-agent/$agent'
import { Route as PkgPkgIdSplatRouteImport } from './routes/pkg/$pkgId/$'

const UiroutesSmokeRoute = UiroutesSmokeRouteImport.update({
  id: '/uiroutes-smoke',
  path: '/uiroutes-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const SweeperRoute = SweeperRouteImport.update({
  id: '/sweeper',
  path: '/sweeper',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeAclRoute = SpikeAclRouteImport.update({
  id: '/spike-acl',
  path: '/spike-acl',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSmokeRoute = SettingsSmokeRouteImport.update({
  id: '/settings-smoke',
  path: '/settings-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgSmokeRoute = PkgSmokeRouteImport.update({
  id: '/pkg-smoke',
  path: '/pkg-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PkgKernelStatusRoute = PkgKernelStatusRouteImport.update({
  id: '/pkg-kernel-status',
  path: '/pkg-kernel-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PermsSmokeRoute = PermsSmokeRouteImport.update({
  id: '/perms-smoke',
  path: '/perms-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSmokeRoute = McpSmokeRouteImport.update({
  id: '/mcp-smoke',
  path: '/mcp-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const IykeSmokeRoute = IykeSmokeRouteImport.update({
  id: '/iyke-smoke',
  path: '/iyke-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeMountSmokeRoute = IframeMountSmokeRouteImport.update({
  id: '/iframe-mount-smoke',
  path: '/iframe-mount-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CronSmokeRoute = CronSmokeRouteImport.update({
  id: '/cron-smoke',
  path: '/cron-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeAssetsSmokeRoute = ClaudeAssetsSmokeRouteImport.update({
  id: '/claude-assets-smoke',
  path: '/claude-assets-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRouteRoute = VideoRouteRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRouteRoute = StoryboardRouteRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRouteRoute = EmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRouteRoute = ClaudeRouteRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() => import('./routes/video/index.lazy').then((d) => d.Route))
const TriageIndexRoute = TriageIndexRouteImport.update({
  id: '/triage/',
  path: '/triage/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardIndexRoute = StoryboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoryboardRouteRoute,
} as any).lazy(() =>
  import('./routes/storyboard/index.lazy').then((d) => d.Route),
)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const ClaudeIndexRoute = ClaudeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoQueueRoute = VideoQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() => import('./routes/video/queue.lazy').then((d) => d.Route))
const VideoCompositionIdRoute = VideoCompositionIdRouteImport.update({
  id: '/$compositionId',
  path: '/$compositionId',
  getParentRoute: () => VideoRouteRoute,
} as any).lazy(() =>
  import('./routes/video/$compositionId.lazy').then((d) => d.Route),
)
const StoryboardIdRoute = StoryboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoryboardRouteRoute,
} as any).lazy(() =>
  import('./routes/storyboard/$id.lazy').then((d) => d.Route),
)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIdRoute = EmailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const ClaudeSkillsRoute = ClaudeSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeMcpsRoute = ClaudeMcpsRouteImport.update({
  id: '/mcps',
  path: '/mcps',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeHooksRoute = ClaudeHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const ClaudeCommandsRoute = ClaudeCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => ClaudeRouteRoute,
} as any)
const PkgPkgIdRouteRoute = PkgPkgIdRouteRouteImport.update({
  id: '/pkg/$pkgId',
  path: '/pkg/$pkgId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsByAgentIndexRoute = SessionsByAgentIndexRouteImport.update({
  id: '/by-agent/',
  path: '/by-agent/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsAllIndexRoute = SessionsAllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/$sessionId/',
  path: '/$sessionId/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const EmailsDraftsIndexRoute = EmailsDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => EmailsRouteRoute,
} as any)
const SessionsByAgentAgentRoute = SessionsByAgentAgentRouteImport.update({
  id: '/by-agent/$agent',
  path: '/by-agent/$agent',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const PkgPkgIdSplatRoute = PkgPkgIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PkgPkgIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/emails': typeof EmailsRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/storyboard': typeof StoryboardRouteRouteWithChildren
  '/video': typeof VideoRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/emails/$id': typeof EmailsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/calendar/': typeof CalendarIndexRoute
  '/claude/': typeof ClaudeIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storyboard/': typeof StoryboardIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/video/': typeof VideoIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/emails/drafts/': typeof EmailsDraftsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/emails/$id': typeof EmailsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/calendar': typeof CalendarIndexRoute
  '/claude': typeof ClaudeIndexRoute
  '/emails': typeof EmailsIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/storyboard': typeof StoryboardIndexRoute
  '/triage': typeof TriageIndexRoute
  '/video': typeof VideoIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/emails/drafts': typeof EmailsDraftsIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/sessions/all': typeof SessionsAllIndexRoute
  '/sessions/by-agent': typeof SessionsByAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude': typeof ClaudeRouteRouteWithChildren
  '/emails': typeof EmailsRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/storyboard': typeof StoryboardRouteRouteWithChildren
  '/video': typeof VideoRouteRouteWithChildren
  '/claude-assets-smoke': typeof ClaudeAssetsSmokeRoute
  '/cron-smoke': typeof CronSmokeRoute
  '/iframe-mount-smoke': typeof IframeMountSmokeRoute
  '/install': typeof InstallRoute
  '/iyke-smoke': typeof IykeSmokeRoute
  '/mcp-smoke': typeof McpSmokeRoute
  '/packages': typeof PackagesRoute
  '/perms-smoke': typeof PermsSmokeRoute
  '/pkg-kernel-status': typeof PkgKernelStatusRoute
  '/pkg-smoke': typeof PkgSmokeRoute
  '/settings-smoke': typeof SettingsSmokeRoute
  '/spike-acl': typeof SpikeAclRoute
  '/sweeper': typeof SweeperRoute
  '/uiroutes-smoke': typeof UiroutesSmokeRoute
  '/pkg/$pkgId': typeof PkgPkgIdRouteRouteWithChildren
  '/claude/commands': typeof ClaudeCommandsRoute
  '/claude/hooks': typeof ClaudeHooksRoute
  '/claude/mcps': typeof ClaudeMcpsRoute
  '/claude/skills': typeof ClaudeSkillsRoute
  '/emails/$id': typeof EmailsIdRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/storyboard/$id': typeof StoryboardIdRoute
  '/video/$compositionId': typeof VideoCompositionIdRoute
  '/video/queue': typeof VideoQueueRoute
  '/calendar/': typeof CalendarIndexRoute
  '/claude/': typeof ClaudeIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storyboard/': typeof StoryboardIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/video/': typeof VideoIndexRoute
  '/pkg/$pkgId/$': typeof PkgPkgIdSplatRoute
  '/sessions/by-agent/$agent': typeof SessionsByAgentAgentRoute
  '/emails/drafts/': typeof EmailsDraftsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/all/': typeof SessionsAllIndexRoute
  '/sessions/by-agent/': typeof SessionsByAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude'
    | '/emails'
    | '/sessions'
    | '/storyboard'
    | '/video'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/pkg/$pkgId'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/emails/$id'
    | '/settings/backup'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/calendar/'
    | '/claude/'
    | '/emails/'
    | '/inbox/'
    | '/sessions/'
    | '/settings/'
    | '/storyboard/'
    | '/triage/'
    | '/video/'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/emails/drafts/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/pkg/$pkgId'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/emails/$id'
    | '/settings/backup'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/calendar'
    | '/claude'
    | '/emails'
    | '/inbox'
    | '/sessions'
    | '/settings'
    | '/storyboard'
    | '/triage'
    | '/video'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/emails/drafts'
    | '/sessions/$sessionId'
    | '/sessions/all'
    | '/sessions/by-agent'
  id:
    | '__root__'
    | '/'
    | '/claude'
    | '/emails'
    | '/sessions'
    | '/storyboard'
    | '/video'
    | '/claude-assets-smoke'
    | '/cron-smoke'
    | '/iframe-mount-smoke'
    | '/install'
    | '/iyke-smoke'
    | '/mcp-smoke'
    | '/packages'
    | '/perms-smoke'
    | '/pkg-kernel-status'
    | '/pkg-smoke'
    | '/settings-smoke'
    | '/spike-acl'
    | '/sweeper'
    | '/uiroutes-smoke'
    | '/pkg/$pkgId'
    | '/claude/commands'
    | '/claude/hooks'
    | '/claude/mcps'
    | '/claude/skills'
    | '/emails/$id'
    | '/settings/backup'
    | '/storyboard/$id'
    | '/video/$compositionId'
    | '/video/queue'
    | '/calendar/'
    | '/claude/'
    | '/emails/'
    | '/inbox/'
    | '/sessions/'
    | '/settings/'
    | '/storyboard/'
    | '/triage/'
    | '/video/'
    | '/pkg/$pkgId/$'
    | '/sessions/by-agent/$agent'
    | '/emails/drafts/'
    | '/sessions/$sessionId/'
    | '/sessions/all/'
    | '/sessions/by-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeRouteRoute: typeof ClaudeRouteRouteWithChildren
  EmailsRouteRoute: typeof EmailsRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  StoryboardRouteRoute: typeof StoryboardRouteRouteWithChildren
  VideoRouteRoute: typeof VideoRouteRouteWithChildren
  ClaudeAssetsSmokeRoute: typeof ClaudeAssetsSmokeRoute
  CronSmokeRoute: typeof CronSmokeRoute
  IframeMountSmokeRoute: typeof IframeMountSmokeRoute
  InstallRoute: typeof InstallRoute
  IykeSmokeRoute: typeof IykeSmokeRoute
  McpSmokeRoute: typeof McpSmokeRoute
  PackagesRoute: typeof PackagesRoute
  PermsSmokeRoute: typeof PermsSmokeRoute
  PkgKernelStatusRoute: typeof PkgKernelStatusRoute
  PkgSmokeRoute: typeof PkgSmokeRoute
  SettingsSmokeRoute: typeof SettingsSmokeRoute
  SpikeAclRoute: typeof SpikeAclRoute
  SweeperRoute: typeof SweeperRoute
  UiroutesSmokeRoute: typeof UiroutesSmokeRoute
  PkgPkgIdRouteRoute: typeof PkgPkgIdRouteRouteWithChildren
  SettingsBackupRoute: typeof SettingsBackupRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TriageIndexRoute: typeof TriageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uiroutes-smoke': {
      id: '/uiroutes-smoke'
      path: '/uiroutes-smoke'
      fullPath: '/uiroutes-smoke'
      preLoaderRoute: typeof UiroutesSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweeper': {
      id: '/sweeper'
      path: '/sweeper'
      fullPath: '/sweeper'
      preLoaderRoute: typeof SweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike-acl': {
      id: '/spike-acl'
      path: '/spike-acl'
      fullPath: '/spike-acl'
      preLoaderRoute: typeof SpikeAclRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-smoke': {
      id: '/settings-smoke'
      path: '/settings-smoke'
      fullPath: '/settings-smoke'
      preLoaderRoute: typeof SettingsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-smoke': {
      id: '/pkg-smoke'
      path: '/pkg-smoke'
      fullPath: '/pkg-smoke'
      preLoaderRoute: typeof PkgSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pkg-kernel-status': {
      id: '/pkg-kernel-status'
      path: '/pkg-kernel-status'
      fullPath: '/pkg-kernel-status'
      preLoaderRoute: typeof PkgKernelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perms-smoke': {
      id: '/perms-smoke'
      path: '/perms-smoke'
      fullPath: '/perms-smoke'
      preLoaderRoute: typeof PermsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-smoke': {
      id: '/mcp-smoke'
      path: '/mcp-smoke'
      fullPath: '/mcp-smoke'
      preLoaderRoute: typeof McpSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iyke-smoke': {
      id: '/iyke-smoke'
      path: '/iyke-smoke'
      fullPath: '/iyke-smoke'
      preLoaderRoute: typeof IykeSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-mount-smoke': {
      id: '/iframe-mount-smoke'
      path: '/iframe-mount-smoke'
      fullPath: '/iframe-mount-smoke'
      preLoaderRoute: typeof IframeMountSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-smoke': {
      id: '/cron-smoke'
      path: '/cron-smoke'
      fullPath: '/cron-smoke'
      preLoaderRoute: typeof CronSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-assets-smoke': {
      id: '/claude-assets-smoke'
      path: '/claude-assets-smoke'
      fullPath: '/claude-assets-smoke'
      preLoaderRoute: typeof ClaudeAssetsSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/triage/': {
      id: '/triage/'
      path: '/triage'
      fullPath: '/triage/'
      preLoaderRoute: typeof TriageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard/': {
      id: '/storyboard/'
      path: '/'
      fullPath: '/storyboard/'
      preLoaderRoute: typeof StoryboardIndexRouteImport
      parentRoute: typeof StoryboardRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/': {
      id: '/emails/'
      path: '/'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/claude/': {
      id: '/claude/'
      path: '/'
      fullPath: '/claude/'
      preLoaderRoute: typeof ClaudeIndexRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/queue': {
      id: '/video/queue'
      path: '/queue'
      fullPath: '/video/queue'
      preLoaderRoute: typeof VideoQueueRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/video/$compositionId': {
      id: '/video/$compositionId'
      path: '/$compositionId'
      fullPath: '/video/$compositionId'
      preLoaderRoute: typeof VideoCompositionIdRouteImport
      parentRoute: typeof VideoRouteRoute
    }
    '/storyboard/$id': {
      id: '/storyboard/$id'
      path: '/$id'
      fullPath: '/storyboard/$id'
      preLoaderRoute: typeof StoryboardIdRouteImport
      parentRoute: typeof StoryboardRouteRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$id': {
      id: '/emails/$id'
      path: '/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof EmailsIdRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/claude/skills': {
      id: '/claude/skills'
      path: '/skills'
      fullPath: '/claude/skills'
      preLoaderRoute: typeof ClaudeSkillsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/mcps': {
      id: '/claude/mcps'
      path: '/mcps'
      fullPath: '/claude/mcps'
      preLoaderRoute: typeof ClaudeMcpsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/hooks': {
      id: '/claude/hooks'
      path: '/hooks'
      fullPath: '/claude/hooks'
      preLoaderRoute: typeof ClaudeHooksRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/claude/commands': {
      id: '/claude/commands'
      path: '/commands'
      fullPath: '/claude/commands'
      preLoaderRoute: typeof ClaudeCommandsRouteImport
      parentRoute: typeof ClaudeRouteRoute
    }
    '/pkg/$pkgId': {
      id: '/pkg/$pkgId'
      path: '/pkg/$pkgId'
      fullPath: '/pkg/$pkgId'
      preLoaderRoute: typeof PkgPkgIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/by-agent/': {
      id: '/sessions/by-agent/'
      path: '/by-agent'
      fullPath: '/sessions/by-agent/'
      preLoaderRoute: typeof SessionsByAgentIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/all/': {
      id: '/sessions/all/'
      path: '/all'
      fullPath: '/sessions/all/'
      preLoaderRoute: typeof SessionsAllIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/emails/drafts/': {
      id: '/emails/drafts/'
      path: '/drafts'
      fullPath: '/emails/drafts/'
      preLoaderRoute: typeof EmailsDraftsIndexRouteImport
      parentRoute: typeof EmailsRouteRoute
    }
    '/sessions/by-agent/$agent': {
      id: '/sessions/by-agent/$agent'
      path: '/by-agent/$agent'
      fullPath: '/sessions/by-agent/$agent'
      preLoaderRoute: typeof SessionsByAgentAgentRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/pkg/$pkgId/$': {
      id: '/pkg/$pkgId/$'
      path: '/$'
      fullPath: '/pkg/$pkgId/$'
      preLoaderRoute: typeof PkgPkgIdSplatRouteImport
      parentRoute: typeof PkgPkgIdRouteRoute
    }
  }
}

interface ClaudeRouteRouteChildren {
  ClaudeCommandsRoute: typeof ClaudeCommandsRoute
  ClaudeHooksRoute: typeof ClaudeHooksRoute
  ClaudeMcpsRoute: typeof ClaudeMcpsRoute
  ClaudeSkillsRoute: typeof ClaudeSkillsRoute
  ClaudeIndexRoute: typeof ClaudeIndexRoute
}

const ClaudeRouteRouteChildren: ClaudeRouteRouteChildren = {
  ClaudeCommandsRoute: ClaudeCommandsRoute,
  ClaudeHooksRoute: ClaudeHooksRoute,
  ClaudeMcpsRoute: ClaudeMcpsRoute,
  ClaudeSkillsRoute: ClaudeSkillsRoute,
  ClaudeIndexRoute: ClaudeIndexRoute,
}

const ClaudeRouteRouteWithChildren = ClaudeRouteRoute._addFileChildren(
  ClaudeRouteRouteChildren,
)

interface EmailsRouteRouteChildren {
  EmailsIdRoute: typeof EmailsIdRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
  EmailsDraftsIndexRoute: typeof EmailsDraftsIndexRoute
}

const EmailsRouteRouteChildren: EmailsRouteRouteChildren = {
  EmailsIdRoute: EmailsIdRoute,
  EmailsIndexRoute: EmailsIndexRoute,
  EmailsDraftsIndexRoute: EmailsDraftsIndexRoute,
}

const EmailsRouteRouteWithChildren = EmailsRouteRoute._addFileChildren(
  EmailsRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsByAgentAgentRoute: typeof SessionsByAgentAgentRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  SessionsAllIndexRoute: typeof SessionsAllIndexRoute
  SessionsByAgentIndexRoute: typeof SessionsByAgentIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsByAgentAgentRoute: SessionsByAgentAgentRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  SessionsAllIndexRoute: SessionsAllIndexRoute,
  SessionsByAgentIndexRoute: SessionsByAgentIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

interface StoryboardRouteRouteChildren {
  StoryboardIdRoute: typeof StoryboardIdRoute
  StoryboardIndexRoute: typeof StoryboardIndexRoute
}

const StoryboardRouteRouteChildren: StoryboardRouteRouteChildren = {
  StoryboardIdRoute: StoryboardIdRoute,
  StoryboardIndexRoute: StoryboardIndexRoute,
}

const StoryboardRouteRouteWithChildren = StoryboardRouteRoute._addFileChildren(
  StoryboardRouteRouteChildren,
)

interface VideoRouteRouteChildren {
  VideoCompositionIdRoute: typeof VideoCompositionIdRoute
  VideoQueueRoute: typeof VideoQueueRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

const VideoRouteRouteChildren: VideoRouteRouteChildren = {
  VideoCompositionIdRoute: VideoCompositionIdRoute,
  VideoQueueRoute: VideoQueueRoute,
  VideoIndexRoute: VideoIndexRoute,
}

const VideoRouteRouteWithChildren = VideoRouteRoute._addFileChildren(
  VideoRouteRouteChildren,
)

interface PkgPkgIdRouteRouteChildren {
  PkgPkgIdSplatRoute: typeof PkgPkgIdSplatRoute
}

const PkgPkgIdRouteRouteChildren: PkgPkgIdRouteRouteChildren = {
  PkgPkgIdSplatRoute: PkgPkgIdSplatRoute,
}

const PkgPkgIdRouteRouteWithChildren = PkgPkgIdRouteRoute._addFileChildren(
  PkgPkgIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeRouteRoute: ClaudeRouteRouteWithChildren,
  EmailsRouteRoute: EmailsRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  StoryboardRouteRoute: StoryboardRouteRouteWithChildren,
  VideoRouteRoute: VideoRouteRouteWithChildren,
  ClaudeAssetsSmokeRoute: ClaudeAssetsSmokeRoute,
  CronSmokeRoute: CronSmokeRoute,
  IframeMountSmokeRoute: IframeMountSmokeRoute,
  InstallRoute: InstallRoute,
  IykeSmokeRoute: IykeSmokeRoute,
  McpSmokeRoute: McpSmokeRoute,
  PackagesRoute: PackagesRoute,
  PermsSmokeRoute: PermsSmokeRoute,
  PkgKernelStatusRoute: PkgKernelStatusRoute,
  PkgSmokeRoute: PkgSmokeRoute,
  SettingsSmokeRoute: SettingsSmokeRoute,
  SpikeAclRoute: SpikeAclRoute,
  SweeperRoute: SweeperRoute,
  UiroutesSmokeRoute: UiroutesSmokeRoute,
  PkgPkgIdRouteRoute: PkgPkgIdRouteRouteWithChildren,
  SettingsBackupRoute: SettingsBackupRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TriageIndexRoute: TriageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
